### ISSUE TITLE
Running subsampling to draw rarefaction curves  with only FL reads？

### ISSUE THREAD

**Issue by linglingtingfei** [Magdoll/cDNA_Cupcake#10]
@Magdoll ，
If I have only FL reads, can I run subsampling to draw rarefaction curves after collapsing read without Iso-Seq cluster? I want to use  tofu_wrap to cluster fl reads but I don't have other files that need to be required. Is that OK?

**Comment by Magdoll** [comment]
Hi @linglingtingfei ,

If you only have FL reads, you need to first map them and collapse them --- so get you unique isoforms and the associated counts. As long as you satisfy the input requirement you can run rarefaction curves.

--Liz
