### ISSUE TITLE
Questions about the result of running collapse_isoforms_by_sam.py

### ISSUE THREAD

**Issue by CrazyHsu** [Magdoll/cDNA_Cupcake#100]
Hi Liz,

Thank you for providing us a nice tools for collapsing the transcripts!
I have a question about `gene_id` attribute in the **gff** of running `collapse_isoforms_by_sam.py`. The version i used is `Py2_v8.7.x`, but i get some different results from the version `7.6` and the version of python is 2.7. Here is my output from the two versions.
Py2_v8.7.x
```
caffold_437    PacBio  transcript      516     979     .       +       .       gene_id "PB"; transcript_id "PB.1.1";
scaffold_437    PacBio  exon    516     979     .       +       .       gene_id "PB"; transcript_id "PB.1.1";
scaffold_257    PacBio  transcript      22      1099    .       +       .       gene_id "PB"; transcript_id "PB.2.1";
scaffold_257    PacBio  exon    22      150     .       +       .       gene_id "PB"; transcript_id "PB.2.1";
```
7.6
```
scaffold_97     PacBio  transcript      1608    2972    .       +       .       gene_id "PB.1"; transcript_id "PB.1.1";
scaffold_97     PacBio  exon    1608    2402    .       +       .       gene_id "PB.1"; transcript_id "PB.1.1";
scaffold_97     PacBio  exon    2520    2972    .       +       .       gene_id "PB.1"; transcript_id "PB.1.1";
```
Why the `gene_id` changed from "PB.XXX" in 7.6 to "PB" in Py2_v8.7.x? Is there some bugs in new version? Or, i have missed something? Please let me know! Thanks!

**Comment by Magdoll** [comment]
Hi @CrazyHsu ,
This is a bug I need to fix. Will update issue when it is fixed. Thanks for notifying me.
--Liz

**Comment by CrazyHsu** [comment]
> Hi @CrazyHsu ,
> This is a bug I need to fix. Will update issue when it is fixed. Thanks for notifying me.
> --Liz

@Magdoll Thanks for your quick response! I'm looking forward to the new version.

**Comment by Magdoll** [comment]
Hi @CrazyHsu ,
This is now fixed. For Python 2.7, this is [v8.7.4](https://github.com/Magdoll/cDNA_Cupcake/tree/v8.7.4)

For Python 3.7, it is [v9.0.3](https://github.com/Magdoll/cDNA_Cupcake/tree/v9.0.3)
