### ISSUE TITLE
v9.0.3 installation error

### ISSUE THREAD

**Issue by yuqiu77** [Magdoll/cDNA_Cupcake#104]
When I try to install the latest py3.7 version of cDNA_cupcake,  I got the following error msg:

`
Searching for bcbiogff

Reading https://pypi.org/simple/bcbiogff/

Couldn't find index page for 'bcbiogff' (maybe misspelled?)

Scanning index of all packages (this may take a while)

Reading https://pypi.org/simple/

No local packages or working download links found for bcbiogff

error: Could not find suitable distribution for Requirement.parse('bcbiogff')
`

Installation cmds were:

`
conda install -y biopython bx-python cython bcbiogff gffread psutil pysam

git clone https://github.com/Magdoll/cDNA_Cupcake.git

cd cDNA_Cupcake/

python setup.py build

python setup.py install
`

Change the setup.py install_requires from "bcbiogff" to "bcbio-gff" would solve the issue.

**Comment by Magdoll** [comment]
Fixed in v9.1.1
https://github.com/Magdoll/cDNA_Cupcake/tree/v9.1.1
