### ISSUE TITLE
How to cite this pipeline?

### ISSUE THREAD

**Issue by conchoecia** [Magdoll/cDNA_Cupcake#109]
Hi!

I want to cite this pipeline in a paper. What is your recommended way to do so?

I used this information to collapse haplotypes: https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step

Thank you-
Darrin

**Comment by Magdoll** [comment]
Hi @conchoecia ,
Thanks for using Cupcake. You could say "....data was processed using the Cupcake tool (https://github.com/Magdoll/cDNA_Cupcake)" in the main section of the paper, and in the methods/supplement section, detail the scripts used along with the parameters.

Thanks,
-Liz
