### ISSUE TITLE
installing error for Cupcake ToFU

### ISSUE THREAD

**Issue by linglingtingfei** [Magdoll/cDNA_Cupcake#11]
@Magdoll 
I tried to install latest cupcake tofu  using conda, but it produced a error（shown on screenshot below）.

![qq 20170818222354](https://user-images.githubusercontent.com/20789616/29463203-777d6966-8464-11e7-84f0-4e62c2b5355b.jpg)

**Comment by Magdoll** [comment]
Hi @linglingtingfei ,

Sorry about this! I have fixed the setup.py. Please update or re-download your GitHub repo. It should work now.

--Liz
