### ISSUE TITLE
error in chain_sample.py

### ISSUE THREAD

**Issue by SeoChaehwa** [Magdoll/cDNA_Cupcake#114]
Hi,

I got the hq fasta file using isoseq3 and collapse by cDNA_cupcake 11.0.0(with --cpus 60) with GRCh38 genome. And then I'm trying to chain_sample.py with 20 samples.

In 7th sample chaining, show below error messages. 
"Expects to see tmp_7th.0.gff,tmp_7th.0.mega_info.txt,tmp_7th.0.group.txt but one or more files are missing! Abort!"
I found some of splited file size are empty in 7th sample directory.
and The size of the newly created files gradually increases. It almost used 1T memory during chaining.
I am wondering if it's right files.

 85M Apr  8 16:04 tmp_2nd.gff
2.5M Apr  8 16:04 tmp_2nd.mega_info.txt
3.3M Apr  8 16:04 tmp_2nd.group.txt
245M Apr  8 16:07 tmp_3rd.gff
4.9M Apr  8 16:07 tmp_3rd.mega_info.txt
9.5M Apr  8 16:07 tmp_3rd.group.txt
837M Apr  8 16:15 tmp_4th.gff
 13M Apr  8 16:15 tmp_4th.mega_info.txt
 35M Apr  8 16:15 tmp_4th.group.txt
 11G Apr  8 16:58 tmp_5th.gff
134M Apr  8 16:58 tmp_5th.mega_info.txt
452M Apr  8 16:58 tmp_5th.group.txt
328G Apr 10 02:33 tmp_6th.gff
3.4G Apr 10 02:33 tmp_6th.mega_info.txt
 14G Apr 10 02:33 tmp_6th.group.txt
1.7K Apr 10 10:26 chain.config

I used minimap2 with -ax splice -t 30 -uf --secondary=no -C5 and sort -k 3,3 -k 4,4n.
size of each collapsed gff file are 7.5M ~ 48M and mean size 28M.

sincerely,
- chaehwa.

**Comment by Magdoll** [comment]
Hi @SeoChaehwa ,
I see on the 6th chain the GFF file suddenly exploded...it went from 11G (5th) to 328G (6th)...! That might be related.

Are some of the samples unusually large? It's hard to imagine you have a sample GFF that is >100GB.

-Liz

**Comment by SeoChaehwa** [comment]
Hi @Magdoll,
No, each sample GFF file size aren't over 50M.

 35M Apr  5 14:25 1st.collapsed.gff
 48M Apr  5 13:49 2nd.Gastric.collapsed.gff
 29M Apr  5 14:00 3rd.collapsed.gff
 28M Apr  5 14:37 4th.collapsed.gff
 34M Apr  5 13:54 5th.collapsed.gff
 19M Apr  8 09:49 6th.collapsed.gff
 39M Apr 13 03:50 7th.collapsed.gff
 26M Apr  4 16:44 8th.collapsed.gff
 46M Apr  5 12:43 9th.collapsed.gff
7.5M Apr  5 12:32 10th.collapsed.gff
 16M Apr  5 13:25 11th.collapsed.gff
 29M Apr  5 13:03 12th.collapsed.gff
 32M Apr  5 13:15 13th.collapsed.gff
 30M Apr  5 13:41 14th.collapsed.gff
 20M Apr  4 18:51 15th.collapsed.gff
 33M Apr  5 12:48 16th.collapsed.gff
 22M Apr  5 12:37 17th.collapsed.gff
 21M Apr  5 13:29 18th.collapsed.gff
 26M Apr  5 13:09 19th.collapsed.gff
 26M Apr  5 13:20 20th.collapsed.gff

-Chaehwa.

**Comment by wanghua1981** [comment]
Hi Liz,
I have met the same problem when use the chain_sample.py, one of my sample (.gff, group.txt file) is splited into 9 parts (0-8), but the No.8 is acturally the blank file, then the "Expects to see tmp_bf.8.gff,tmp_bf.8.mega_info.txt,tmp_bf.8.group.txt but one or more files are missing! Abort!" error report appears, is there any way I can fix this problem, many thanks!
Hua

**Comment by NeuzaRM** [comment]
Hello,
I found the exact same issue as Hua.
Before the error reported by Hua, this other error comes up:
"ERROR:Sanity checking /labs/mtfuller/ProjectCompleteIsoform/NeuzaM_CCS_72-2/renamed.collapsed.gff.split8 is GFF3 format: expected 9 tab-delimited fields but saw 1! Abort!"
The file "renamed.collapsed.gff" looks like a normal GFF3 though.
Thank you
Neuza

**Comment by Magdoll** [comment]
Hi @NeuzaRM , can you share the input files w me confidentially for me to debug?
-Liz

**Comment by NeuzaRM** [comment]
Hi Liz,
Thanks a lot for your reply.
How should I share the files with you? Is there a way to share them through github?
I'm sorry but I've just created my account and didn't explore much how to use it yet.

Thanks
Neuza
________________________________

**Comment by Magdoll** [comment]
Hi @NeuzaRM , please give me an email so I can send a data upload request.
Thanks,
-Liz

**Comment by NeuzaRM** [comment]
nmatias@stanford.edu


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by noor-albader** [comment]
Hi I am experiencing the same problem with chain_sample.py 
The specific error is as follows: `Expects to see tmp_72h-Rhizome.8.gff,tmp_72h-Rhizome.8.mega_info.txt,tmp_72h-Rhizome.8.group.txt but one or more files are missing! Abort!`
This sample is one of 21 samples I am trying to chain together and a 8th split temp file was never created. 
Any ideas how to circumvent this error? Thanks!

**Comment by NeuzaRM** [comment]
Thanks for checking! I have no idea what could be causing the issue. Does this happen with other files? It seems that the same error was mentioned by @wanghua1981

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Magdoll** [comment]
@NeuzaRM  - a file upload request has been sent to your email. Please check.

@noor-albader  -well, clearly something is wrong, so I would not try to circumvent the error :P do you want to share your input file with me as well? (if yes, please give me an email to request files)

**Comment by noor-albader** [comment]
@Magdoll your right, poor word choice. Lets id the problem lol 
email: noor.albader@kaust.edu.sa
thanks again!

**Comment by Magdoll** [comment]
Hi @noor-albader  - request has been sent.
Hi @NeuzaRM - thx for data. Will look into it.

**Comment by Magdoll** [comment]
Update: for @NeuzaRM  - i ran chain_samples.py and was able to complete it. Results have been sent back hope to be repeated.
for @noor-albader  - looking into data now.

**Comment by Magdoll** [comment]
@noor-albader  - are you aware that you did not upload all the files for 42d-Root? You may have exceeded the file limit.
Also, which particular set of files were you using?
Is it *.polished.cupcake.collapsed.filtered.abundance.txt?

**Comment by noor-albader** [comment]
@Magdoll yes, I have received the email of the files you sent (downloading now). Too bad I reached mem limit and couldn't send the rest of 42d-Root and all of 48h, 72h samples. I will use the updated version of cupcake and try again! Thank you!

**Comment by sarahhp** [comment]
Hi, 
I am still getting the same error as above on my own samples as well the test data with cupcake v12.4.0. 
The split2 file is empty in the test case for me: 

ERROR:Sanity checking /home/sarahhp/pkgs/cDNA_Cupcake/cupcake/test_data/chaining/B/touse.gff.split2 is GFF3 format: expected 9 tab-delimited fields but saw 1! Abort!

Thanks!

**Comment by Magdoll** [comment]
@sarahhp , hmm, can you share the data with me? wonder if it's just another silly edge case I didn't catch on splitting up files properly...

--Liz

**Comment by sarahhp** [comment]
@Magdoll Sure! sarahhp@medisin.uio.no

**Comment by Magdoll** [comment]
Hi @sarahhp ,
I fixed the bug (which was dumb - I didn't handle chormosomes that didn't start with "chr", so your data broke becuz of that *facepalm*). Please update to Cupcake v12.5.

Another thing is I ran chain_samples.py on your data with two sets of params.

```
chain_samples.py collapsed.config count_fl
chain_samples.py --dun-merge-5-shorter collapsed.config count_fl
```

The first, default command will generate a much larger chaining result because it will keep chaining all the transcripts that could be 5' degraded products of each other together. If you run the second command the chained result is a lot smaller. You can play around with it. 

Chaining is especially problematic with single-exon transcripts or lots of transcripts that only differ in their 3' UTR length. YOu can adjust that using `--max_3_diff` param.

Let me know what you find.

```
$ chain_samples.py --help
usage: chain_samples.py [-h] [--fuzzy_junction FUZZY_JUNCTION]
                        [--dun-merge-5-shorter] [--max_3_diff MAX_3_DIFF]
                        [--cpus CPUS]
                        config_file {norm_fl,count_fl}

positional arguments:
  config_file
  {norm_fl,count_fl}    Which count field to use for chained sample (default:
                        count_fl)

optional arguments:
  -h, --help            show this help message and exit
  --fuzzy_junction FUZZY_JUNCTION
                        Max allowed distance in junction to be considered
                        identical (default: 0 bp)
  --dun-merge-5-shorter
                        Don't collapse shorter 5' transcripts (default: off)
  --max_3_diff MAX_3_DIFF
                        Maximum 3' difference allowed (default: 30bp)
  --cpus CPUS           Number of CPUs to use for multi-threading (default: 8)
```

**Comment by sarahhp** [comment]
@Magdoll Thanks so much! v12.5 now works for me.  

I will have a definately play around with different parameters, as ours is a single gene CaptureSeq.

**Comment by Magdoll** [comment]
Good to hear! Closing issue.

**Comment by SziKayLeung** [comment]
Hi Liz, 

A slightly but related issue, upon chaining my targeted samples. I'm getting an error on one of the final samples: 

"Expects to see tmp_Q17.0.gff,tmp_Q17.0.mega_info.txt,tmp_Q17.0.group.txt but one or more files are missing! Abort!"

And when I look into the Q17 folder:
![image](https://user-images.githubusercontent.com/33493350/102385213-7b9e2100-3fc5-11eb-95a0-86512a8b74d9.png)

It appears that the files were split but didn't proceed further with chaining. 

Thanks, 
Szi Kay

**Comment by Magdoll** [comment]
Hi @SziKayLeung ,
I found a related empty file bug in `chain_samples.py` yesterday and have updated to v18.1.0. Can you see if that fixes the issue?

-Liz

**Comment by SziKayLeung** [comment]
Thanks Liz for looking into this, the problem still persists. I've checked the file size of sample Q17 and it looks relatively similar to the other samples

**Comment by Magdoll** [comment]
@SziKayLeung ,
First I notice you don't seem to have actually installed Cupcake?
Make sure you have downloaded the latest Cupcake from GitHub and run `python setup.py build; python setup.py install`

You should be running Cupcake without the `python` before `chain_samples.py` as in:

```
chain_samples.py Chained_Configuration.txt count_fl --dun-merge-5-shorter
```

**Comment by SziKayLeung** [comment]
Hello Liz, 

Thanks for the note. I have reinstalled Cupcake (v18.1) and reran with your command as above. 

However, the problem still persists:
 "Expects to see tmp_S23.0.gff,tmp_S23.0.mega_info.txt,tmp_S23.0.group.txt but one or more files are missing! Abort!"

I have checked the same command but with fewer samples (including S23) and the chaining worked. 
Is there a limit on the number of samples/minimum memory required?

**Comment by Magdoll** [comment]
Hi @SziKayLeung ,
There is not limit on samples and I don't think you've hit memory requirement. Most likely yet another edge case for chaining?

If problem persists with a clean run slack me.
-Liz

**Comment by SichongP** [comment]
Hi,

I'm on 28.0.0 from conda and I'm seeing a similar problem:

> Expects to see tmp_AH1_Muscle.0.gff,tmp_AH1_Muscle.0.mega_info.txt,tmp_AH1_Muscle.0.group.txt but one or more files are missing! Abort!

And on a separate note, when I run chain_samples.py with multiple threads, I see a different error:
```
Traceback (most recent call last):
  File "/home/pengsc/conda_envs/883354778217ffadef6445125f3d5edf/bin/chain_samples.py", line 528, in <module>
    chain_samples_multithread(sample_dirs, sample_names, group_filename, gff_filename, count_filename, args.field_to_use, args.fuzzy_junction, args.allow_5merge, args.max_3_diff, fastq_filename, cpus=args.cpus)
  File "/home/pengsc/conda_envs/883354778217ffadef6445125f3d5edf/bin/chain_samples.py", line 481, in chain_samples_multithread
    if r['tmp_'+c] == 'NA':
KeyError: 'tmp_AH4_Liver'
```

Any idea where the error could've come from?

**Comment by ramin-shirali** [comment]
@Magdoll Hi. I also have a similar issue. I'm trying to chain 15 samples using the iterative mode and it is using more than requires more than 2TB of RAM when I'm chaining the 10th sample.
Is there any update on this issue?
