### ISSUE TITLE
No results for  "fusion components"

### ISSUE THREAD

**Issue by Br1anChou** [Magdoll/cDNA_Cupcake#116]
Hi @Magdoll ,
Tanks for your useful tools. I successfully ran fusion_finder.py and obtained fusion reads (PBfusion.1, PBfusion.2...) from the *rep.fq files.  But how can  I obtain the fusion component reads (like PBfusion.1.1, PBfusion.1.2; PBfusion.2.1, PBfusion.2.2)?
By the way, I ran collapse_isoforms_by_sam.py and SQANTI2 independently, I noted that the file *classification.txt showed some fusions information. I have no idea about this result, is there any difference and connection between it and the fusion_finder.py results?
Best!

**Comment by Magdoll** [comment]
Hi @Br1anChou ,
Currently `fusion_finder.py` is not outputting individual components. You could potentially use the GFF to output the component sequences, but the order may be incorrect...I'll put this as a ToDo list in the future.

In SQANTI2, if you input the results from collapse (which mostly outputs only continuous alignmnets), "fusions" here would mean technically "readthroughs",  that is,  transcripts that cross over. adjacent genes.

-Liz


-Liz
