### ISSUE TITLE
bx-python in python 2.7

### ISSUE THREAD

**Issue by yichangyu** [Magdoll/cDNA_Cupcake#117]
Hi Liz,

I think bx-python only support python 2.7. But Cupcake is now in python 3. I can't get it work because of the bx-python version problem. Any suggestions for this?

Thanks!

**Comment by Magdoll** [comment]
Hi @yichangyu ,

bx-python is in Python 3.

https://anaconda.org/bioconda/bx-python

I've confirmed it is on my Cupcake environment, see below.

```
(anaCogentPy37) -bash-4.2$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bx
>>> bx.__version__
'0.8.0'
```

**Comment by yichangyu** [comment]
> Hi @yichangyu ,
> 
> bx-python is in Python 3.
> 
> https://anaconda.org/bioconda/bx-python
> 
> I've confirmed it is on my Cupcake environment, see below.
> 
> ```
> (anaCogentPy37) -bash-4.2$ python
> Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
> [GCC 7.3.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import bx
> >>> bx.__version__
> '0.8.0'
> ```

Hi Liz,

Thanks for checking. It must because of my wrong settings then.

Best,
Changyu
