### ISSUE TITLE
Default value error in "Cupcake: supporting scripts for Iso Seq after clustering step" tutorial

### ISSUE THREAD

**Issue by LionOfComarre** [Magdoll/cDNA_Cupcake#119]
On the tutorial page "Cupcake: supporting scripts for Iso Seq after clustering step" in the wiki, it is stated that the default value for the identity cutoff paramter -i for collapse_isoforms_by_sam.py is 0.85, but looking at the actual script the value is 0.95.

**Comment by Magdoll** [comment]
Hi @LionOfComarre ,
You are right...it should be 0.95 now. I'll correct the wiki. Thanks for catching the inconsistency.
-Liz
