### ISSUE TITLE
About after remove polyA...

### ISSUE THREAD

**Issue by sbaheijmcdkhoaj** [Magdoll/cDNA_Cupcake#121]
Hello, may I ask why the cluster step has been removed? And  is there any corresponding literature support for this process?

**Comment by Magdoll** [comment]
Hi @sbaheijmcdkhoaj ,

The cluster step is not removed. We are still recommending running `isoseq3 cluster` in most cases as per [IsoSeq documentation](https://github.com/PacificBiosciences/IsoSeq).

Where did you see this? I'm in the middle of cleaning up the wiki page, so some things may be missing inadvertantly.
-Liz

**Comment by Magdoll** [comment]
Closing unless OP reopens.
