### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by moschmi** [Magdoll/cDNA_Cupcake#123]
@Magdoll 
I just updated Cupcake and I get syntax errors in all .py scripts no matter what I do. With or without arguments. I reinstalled anaconda3, made new environments.... Please help I am in the middle of my analysis.

Here is what I get:
`get_abundance_post_collapse.py
Traceback (most recent call last):
  File "/etc/samba/mos6/user_homes/mos6/anaconda3/envs/anaCogent3/bin/get_abundance_post_collapse.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==8.7.4', 'get_abundance_post_collapse.py')
  File "/etc/samba/mos6/user_homes/mos6/anaconda3/envs/anaCogent3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/etc/samba/mos6/user_homes/mos6/anaconda3/envs/anaCogent3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    code = compile(source, script_filename, 'exec')
  File "/etc/samba/mos6/user_homes/mos6/anaconda3/envs/anaCogent3/lib/python3.7/site-packages/cupcake-8.7.4-py3.7-linux-x86_64.egg/EGG-INFO/scripts/get_abundance_post_collapse.py", line 116
    raise Exception, "Unrecognized id format {0} in {1}!".format(cid, group_filename)
                   ^
SyntaxError: invalid syntax`

**Comment by Magdoll** [comment]
Hi @moschmi 
Pretty sure this is because you have older versions of Cupcake that is still written in Python 2. Please update to the latest version of Cupcake which is using Python 3 :)
-Liz

**Comment by moschmi** [comment]
You are absolutely right @Magdoll !!
I got it with: 
git clone https://github.com/Magdoll/cDNA_Cupcake.git

I downloaded the zipped one, that was the newest...

**Comment by yangchenkang** [comment]
I have a same question with him.

**Comment by Magdoll** [comment]
Hi @yangchenkang ,
Did you update Cupcake through git clone?

**Comment by yangchenkang** [comment]
Hi，Thanks for your response.I downloaded 3.7 Python versions of it on Github.I don’t know why it’s wrong.The questioner is the same as me.



发自我的iPhone


------------------ Original ------------------

**Comment by Magdoll** [comment]
> Hi，Thanks for your response.I downloaded 3.7 Python versions of it on Github.I don’t know why it’s wrong.The questioner is the same as me. 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Elizabeth Tseng <notifications@github.com&gt; Date: Sat,Aug 1,2020 10:53 PM To: Magdoll/cDNA_Cupcake <cDNA_Cupcake@noreply.github.com&gt; Cc: yangchenkang <510908154@qq.com&gt;, Mention <mention@noreply.github.com&gt; Subject: Re: [Magdoll/cDNA_Cupcake] installation issues (#123)

**Comment by Magdoll** [comment]
> Hi，Thanks for your response.I downloaded 3.7 Python versions of it on Github.I don’t know why it’s wrong.The questioner is the same as me. 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Elizabeth Tseng <notifications@github.com&gt; Date: Sat,Aug 1,2020 10:53 PM To: Magdoll/cDNA_Cupcake <cDNA_Cupcake@noreply.github.com&gt; Cc: yangchenkang <510908154@qq.com&gt;, Mention <mention@noreply.github.com&gt; Subject: Re: [Magdoll/cDNA_Cupcake] installation issues (#123)

Hi, the issuers seems to have solved the issue with git clone.....so I'm not sure where you are stuck on...

-Liz

**Comment by yangchenkang** [comment]
Thanks very much！I have solved the question.Now,I can use it normally.



发自我的iPhone


------------------ Original ------------------
