### ISSUE TITLE
UnicodeDecodeError while running Fusion_finder.py

### ISSUE THREAD

**Issue by yazuo0204** [Magdoll/cDNA_Cupcake#125]
Hi,

The error occurs while I am running Fusion_finder.py in the beginning. I tried to change the alignment method from minimap2 to gsnap, but it still there. 
I have read through my bam file and I can't find anything wrong.

Here is my code and error, and first line of my bam file.

`
gsnap -D ./ -d fusion --nthreads=30 -B 5 -s gtf.index.iit -n 2 -Q --nofails --format=sam ../fusiontest.fa > tofu.sam
samtools view -bS -o test.bam test.sam
samtools sort -o test.sorted.bam test.bam

fusion_finder.py --input test.fa -s test.sorted.bam -o Tofu_default

Traceback (most recent call last):
  File "/data/user/zuoya/miniconda3/envs/zuoya/bin/fusion_finder.py", line 400, in <module>
    min_dist_between_loci=args.min_dist_between_loci)
  File "/data/user/zuoya/miniconda3/envs/zuoya/bin/fusion_finder.py", line 293, in fusion_main
    fusion_candidates = find_fusion_candidates(sam_filename, bs.transfrag_len_dict, min_locus_coverage, min_locus_coverage_bp, min_total_coverage, min_dist_between_loci)
  File "/data/user/zuoya/miniconda3/envs/zuoya/bin/fusion_finder.py", line 254, in find_fusion_candidates
    reader = BioReaders.GMAPSAMReader(sam_filename, True, query_len_dict=query_len_dict)
  File "/data/user/zuoya/miniconda3/envs/zuoya/lib/python3.7/site-packages/cupcake/io/BioReaders.py", line 134, in __init__
    line = self.f.readline()
  File "/data/user/zuoya/miniconda3/envs/zuoya/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

0ce7bf8d-062e-4d9b-84fd-eacb467f1775    81      chr1    14408   0       53S263M1D158M140N69M757N16M6D3M6I83M1I44M659N136M9I23M88N133M   *       0       0       AATAGGAGATATGCGGGGCAGGTTGATAGTTGAGATATAACGATGGATGGATGTGCTCAGTTCTTTATTGATTGGTGTGCCATTTTCTCTGGAAGCCTCTTAAGAACACAGTGGCGCAGGCTGGGTGGAGCCGTCCCCCCATGGAGCACAGGCAGACAGAAGTCCCCACCCCAGCTGTGTGGCCTCAGGCCAGCCTTCCGCTCCTTGAAGCTGGTCTCCGCACAGTGCTGGTTCCATCACCCCCACCCAGGGAAGCAGGTCTGAGCAGCTTGTCCTGGCTGTGTCCATGTCAGAGCAATGGCCCAAGTCTGGGTCTGGGGGGAAGGTGTCATGGAGCCCCCTACGATTCCCAGTCGTCCTCGTCCTCCTCTGCCTGTGGCTGCTGCGGTGGCGGCAGAGGAGGGATGGAGTCTGACACGCGGGCAAAGGCTCCTCCGGGCCCCTCACCAGCCCCAGGTCCTTTCCCAGAGATGCCCTTGCGCCTCATGACCAGCTTGTTGAAGAGATCCGACATCAAGTCCCCACCTTGGCTCGTGGCTCTCACTTGCTCCTGCTCCTTCTGCTTCTTCTTCTCCAGCTTTCGCTCCTTCACGCTGCGCAGCTTGGCCTTGCCGATGCCCCCAGCTTGGCGGATGGACTCTAGCAGAGTGGCCCGGCCACCGGAGGGGTCGACCACTTCCCTGGGAGCTCCCTGGACTGAAGGAGACGCGCTGCTGCTGCTGTCGTCCTGCCTGGCGCCTTGGCCTACAGGGGCCGCGGTTGAGGGTGGGAGTGGGGATGCACTGGCCAGCACCTCAGGAGCTGGGGGAGGTGGTGGGGGCGGTGGGGGTGGTGGTGGTGCTGTTAGTACCCCATCTTGTAGGTCTGCCTTGAGAGGCTCGGCTACCTCAGTGTGGAAGGTGGGCAGTTCCGGAATGGTGCCAGGGGCAGAGGGGGCAATGCCGGGGCCCAGGTCGGCACTGTACATGAGGTCGTTGGCAATGCCGGGCAGGTCAGG   *       MD:Z:28G85G19A31A15G8T4A5T42C17^G203G39^CTGCTG26T61A15A106G30T48A43T48A37       NH:i:5  HI:i:3  NM:i:41 SM:i:40 XQ:i:36 X2:i:40 XO:Z:UM XS:A:-

`

Thank you,

Ya

**Comment by Magdoll** [comment]
Hi @yazuo0204 ,
You're supposed to provide a sorted SAM, not sorted BAM file :)
-Liz
