### ISSUE TITLE
meaning of bam tags after cluster step

### ISSUE THREAD

**Issue by lyraealpha** [Magdoll/cDNA_Cupcake#127]
trying to understand bam tags after isoseq3(3.3.0) cluster step here:
example :
transcript/0	4	*	0	255	*	*	0	0	----AGCTA----	*	ib:Z:0,1,2	im:Z:m64014_190506_005857/1705153/ccs,m64014_190506_005857/198112/ccs	is:i:2	ic:i:20	zm:i:0	RG:Z:e4927d21

I tried to find answers from https://github.com/PacificBiosciences/IsoSeq and https://pacbiofileformats.readthedocs.io/en/9.0/BAM.html

but still not understand meaning of ic tag

need help

**Comment by armintoepfer** [comment]
`ic` Sum of number of passes from all ZMWs used to create consensus
That means in your example, the transcript consensus originates from 2 ZMWs with combined 20 passes.

It will be part of the updated Iso-Seq documentation, when we push the next release.
