### ISSUE TITLE
Some questions in getting CCS and demultiplexed reads in article 'Variant phasing and haplotypic expression from long-read sequencing in maize'

### ISSUE THREAD

**Issue by CrazyHsu** [Magdoll/cDNA_Cupcake#128]
Hello Liz,

I have tested data you used in article [**Variant phasing and haplotypic expression from long-read sequencing in maize**](https://www.nature.com/articles/s42003-020-0805-8#Sec9). But after processing the raw data, i got a different total CCS number (4,162,570) with yours (4,898,979). 
Here is the CCS number of my run:
|sample|CCS_number|
|---|---|
|m54026_180421_175219.CCS.bam|282491|
|m54026_180426_005332.CCS.bam|324091|
|m54026_180426_211625.CCS.bam|220544|
|m54026_180504_184612.CCS.bam|290328|
|m54026_180724_211509.CCS.bam|304218|
|m54026_180725_173107.CCS.bam|269573|
|m54026_180726_135101.CCS.bam|231736|
|m54026_180727_101047.CCS.bam|272466|
|m54086_180430_215710.CCS.bam|273622|
|m54086_180503_214050.CCS.bam|179168|
|m54086_180505_143508.CCS.bam|294019|
|m54086_180727_210121.CCS.bam|405974|
|m54119_180504_205900.CCS.bam|225133|
|m54119_180505_171923.CCS.bam|311508|
|m54119_180727_210310.CCS.bam|277699|

After getting CCS reads, I merged all CCS bam into a single CCS bam followed the method you mentioned in the article that "**We pooled the reads from all four lines and processed them using the IsoSeq3 workflow (Fig. 1)**", but in demultiplex step,  lima can't not properly process the bam file with the error '**terminate called without an active exception**'. So i processed each CCS bam with corresponding primers file respectively, it still could't work well with errors that some CCS bam don't have the barcode **ERROR: Could not find matching barcodes! Check that the set of barcodes contains the used sequences and the correct mode has been selected: same or different.**. 

The question is i don't know whether there is inproper step in processing the data, can you please point out which step is incorrect or show me your execution code? Thank you.

My ```ccs``` version is ```ccs 4.2.0 (commit v4.2.0)```, ```isoseq3``` version is ```isoseq3 3.3.0 (commit v3.3.0)```, and ```lima``` version is ```lima 1.9.0 (commit v1.9.0)```. 

Here is my code to get CCS bam and pool all CCS bam into a single file:
```
ccs *.subreads.bam *.CCS.bam --min-rq 0.9
ls *.CCS.bam > CCS.bam.list
samtools cat -b CCS.bam.list -o merged.CCS.bam
lima merged.CCS.bam primers.fa merged.fl.bam --isoseq
```
Here is the primer fasta sequence:
```
$ cat primer.fa
>5p
AAGCAGTGGTATCAACGCAGAGTACATGGGG
>B73_embryo_3p
ATGACGCATCGTCTGAGTACTCTGCGTTGATACCACTGCTT
>Ki11_embryo_3p
GAGTGCTACTCTAGTAGTACTCTGCGTTGATACCACTGCTT
>Ki11_B73_embryo_3p
GCATATAGTAGAGATCGTACTCTGCGTTGATACCACTGCTT
>B73_Ki11_embryo_3p
CACGATAGTCGCTATGGTACTCTGCGTTGATACCACTGCTT
>B73_endo_3p
GCAGAGTCATGTATAGGTACTCTGCGTTGATACCACTGCTT
>Ki11_endo_3p
CATGTACTGATACACAGTACTCTGCGTTGATACCACTGCTT
>Ki11_B73_endo_3p
CAGCAGTATAGACTGTGTACTCTGCGTTGATACCACTGCTT
>B73_Ki11_endo_3p
CACACGCGCGTGCTCGGTACTCTGCGTTGATACCACTGCTT
>B73_root_3p
TCTCTCACAGTCGAGCGTACTCTGCGTTGATACCACTGCTT
>Ki11_root_3p
TGTGATACTGCGAGCAGTACTCTGCGTTGATACCACTGCTT
>Ki11_B73_root_3p
TCGCTCTAGAGTGTGAGTACTCTGCGTTGATACCACTGCTT
>B73_Ki11_root_3p
ACTGTCTCTCGCAGCGGTACTCTGCGTTGATACCACTGCTT
```

Here is my code to demultiplex each CCS bam:
```
ccs *.subreads.bam *.CCS.bam --min-rq 0.9
lima *.CCS.bam primer_*.fa *.fl.bam --isoseq --peek-guess
```
Here is example primer_*.fa(B73) sequence:
```
>5p
AAGCAGTGGTATCAACGCAGAGTACATGGGG
>B73_embryo_3p
ATGACGCATCGTCTGAGTACTCTGCGTTGATACCACTGCTT
>B73_endo_3p
GCAGAGTCATGTATAGGTACTCTGCGTTGATACCACTGCTT
>B73_root_3p
TCTCTCACAGTCGAGCGTACTCTGCGTTGATACCACTGCTT
```

**Comment by CrazyHsu** [comment]
And there is an another question to be confirmed that whether the overhang in **The 5′ primer consists of the Clontech SMARTer cDNA primer with an ATGGG overhang.** is "ATGGG". In my experience, the overhang usually is "ATGGGG". So, to test whether the overhang is "ATGGG" or "ATGGGG", I extracted the first 31 bp of head 10,000 lines in CCS bam, and then ran multiple alignment in 10,000 lines with muscle, the results shows that the overhang is like to be "ATGGGG". Hope you can check it. Thanks.
[m54026_180426_005332.A.head.muscle.clw.txt](https://github.com/Magdoll/cDNA_Cupcake/files/5202189/m54026_180426_005332.A.head.muscle.clw.txt)

**Comment by Magdoll** [comment]
Hi @CrazyHsu  - re: ATGGG(G) - the actual overhang is ATGGG. Also actual RNA transcripts do start with "G"s, too. So there's a tradeoff with using 3 or 4 Gs. But, using either 3 or 4 is fine 👍 
I'll answer the other q in a bit.

**Comment by CrazyHsu** [comment]
Thanks for your prompt reply. If the overhang is ATGGG, there is a big possibility that the difference in the CCS number between yours and mine caused by it, but we'd better check it.

**Comment by Magdoll** [comment]
Hi @CrazyHsu ,
The ATGGG(G) sequence different should not be the main reason why CCS numbers are different - I had to just first make sure that the primer sequences you listed were correct and I've confirmed they are.

re: CCS numbers - different CCS versions *and* different CCS parameters can result in pretty dramatic number changes. 

The paper CCS was run with SMRT Link 6.0, CCS parameters min pass 1, min accuracy 0.80, polish OFF, and a few other parameters that are since now not in use or not exposed.

Just an idea on how CCS params have changed - for the Iso-Seq data coming off recently we are going with the new CCS (currently v4.2.0) with min 3 pass min accuracy 0.90 and polish=ON. So you can see how all these differences can add up.

--Liz

**Comment by CrazyHsu** [comment]
@Magdoll Thank you for your confirmation and suggestions, I'll try it.
