### ISSUE TITLE
Best Practice for Multiple Sequel II Samples

### ISSUE THREAD

**Issue by nathanhaigh** [Magdoll/cDNA_Cupcake#130]
I have data from 5 samples and am trying to figure out the best way to generate gene models across the samples. I've mapped the FASTA reads to the genome (no prior gene models available).

I have managed to get cupcake to work across each of the 5 samples using the following approaches:

1. Collapse intra-sample redundant isoforms using `collapse_isoforms_by_sam.py`
2. Calculate isoform support using `get_abundance_post_collapse.py`
3. Filter out isoforms with < 10 FL reads and remove isoforms which a likely degradation products using `filter_by_count.py` and `filter_away_subset.py`

However, I'd like to do these steps across samples. That is remove redundant isoforms between samples.

I've played with `chain_samples.py` but it seems to only work on the sample data coming from step 1-2 above. How do I filter isoforms based on the combined coverage across the samples and remove isoforms which are likely degradation products from across samples?

**Comment by Magdoll** [comment]
Hi @nathanhaigh ,

`chain_samples.py` *will* work with the output from step (3). What is your `samples.config` file?

**Comment by nathanhaigh** [comment]
Thanks @Magdoll! I got this working by setting the `GFF_FILENAME` and `COUNT_FILENAME` variables in `sample.config` to point to the outputs of `chain_samples.py`:

```
GROUP_FILENAME=touse.collapsed.group.txt
GFF_FILENAME=touse.collapsed.min_fl_10.filtered.gff
COUNT_FILENAME=touse.collapsed.min_fl_10.filtered.abundance.txt
```

**Comment by Magdoll** [comment]
Hi @nathanhaigh  yes that is how you do it ;)
