### ISSUE TITLE
Some problems with the association file to run Isophase 

### ISSUE THREAD

**Issue by pailloufat-stack** [Magdoll/cDNA_Cupcake#131]
Hi Magdoll,

I try to run the script select_loci_to_phase.py from cDNA_Cupcake. I need 4 files :
-	The reference fasta file : I have 
-	The FLNC fastq file : I have
-	The GFF file : I have (I got it from isoseq3 collapse tool) 
-	The association file : I also ran isoseq3 collapse to get it , but the select_loci_to_phase.py can’t read it. I mean, it looks like this :
 
```
id                                                                                    pbid
m64071_200716_144843/136382325/ccs          PB.1.1
m64071_200716_144843/139397143/ccs          PB.1.1
m64071_200716_144843/109906633/ccs          PB.2.1
m64071_200716_144843/4524184/ccs               PB.2.1
m64071_200716_144843/62719995/ccs             PB.2.2
m64071_200716_144843/154600415/ccs            PB.2.2
m64071_200716_144843/11338658/ccs             PB.2.3
m64071_200716_144843/43386476/ccs             PB.2.3
m64071_200716_144843/131467912/ccs          PB.2.4
```
 
and when I run select_loci_to_phase.py (with the expected files) , I have that error message :
 
```
Reading genome...
Reading genome fasta ../GCF_004010815.1_ASM401081v1_genomic.fa....
Reading FLNC file...
Reading read_stat....
Traceback (most recent call last):
  File "/opt/apps/python-3.7.1/gcc-8.1.0/cDNA_Cupcake-12.5/bin/phasing/utils/select_loci_to_phase.py", line 258, in <module>
    select_loci_to_phase(args, genome_d)
  File "/opt/apps/python-3.7.1/gcc-8.1.0/cDNA_Cupcake-12.5/bin/phasing/utils/select_loci_to_phase.py", line 164, in select_loci_to_phase
    tally_by_loci, poor_zmws_not_in_rich = read_read_stat(args.stat_filename, rich_zmws)
  File "/opt/apps/python-3.7.1/gcc-8.1.0/cDNA_Cupcake-12.5/bin/phasing/utils/select_loci_to_phase.py", line 65, in read_read_stat
    stat_filename, reader.fieldnames))
Exception: Expected fields `pbid`, `is_fl`, and `stat` in bc1004.read_stat.txt but only saw: ['id', 'pbid']
```
 

So, I can make a trick in order to « false » that association file with :
 
 
```
awk 'BEGIN { FS="\t"; OFS="\t" };
FNR == 1 { print $1,$2,"is_fl","stat",$NF };
FNR  > 1 { print $1,$2,"Y","unique",$NF }' bc1006.read_stat.txt
``` 
 
 
That gives :
 
 
```
id                                                                            pbid         is_fl  stat       pbid
m64071_200716_144843/114034266/ccs  PB.1.1       Y      unique  PB.1.1
m64071_200716_144843/133760316/ccs  PB.1.1       Y      unique  PB.1.1
m64071_200716_144843/152699228/ccs  PB.1.1       Y      unique  PB.1.1
m64071_200716_144843/160959102/ccs  PB.1.1       Y      unique  PB.1.1
m64071_200716_144843/167183037/ccs  PB.1.1       Y      unique  PB.1.1
m64071_200716_144843/85068275/ccs   PB.1.2       Y      unique  PB.1.2
m64071_200716_144843/82379956/ccs   PB.1.2       Y      unique  PB.1.2
m64071_200716_144843/48169276/ccs   PB.1.2       Y      unique  PB.1.2
m64071_200716_144843/117442784/ccs  PB.1.3       Y      unique  PB.1.3
```
 
 
It looks like this now, , the select_loci_to_phase.py script « worked » but the problem is that didn’t give me any result. No transcripts are read..
 
So if you could have a look on that problem, it could be nice. I would like to get the good association file with the good expected columns… 
 
Bests,
 
Paillou

**Comment by Magdoll** [comment]
Hi @pailloufat-stack ,
(1) I think you have two `pbid` field in there, not sure if that'll cause an issue with the reader.
(2) make sure everything is tab-delimited
(3) did you get any output messages? importantly you should see messages like

```
Reading FLNC file...
Reading read_stat....
Total 100 loci read. 3 has >=  40 coverage
```
This last line is important - if all your genes have less than 40 PacBio FL reads, IsoPhase will not output any phasing directories.

**Comment by pailloufat-stack** [comment]
Hi  ,

Thanks for your reply. You're right, I didn't pay attention to the association file. I needed to remove the last column, and it worked.

On the fact I created a "fake" association file by adding the two necessary columns : `is_fl` and `stat` , could it false the results?

**Comment by Magdoll** [comment]
Hi @pailloufat-stack , the way you added `is_fl` and `stat` is fine! They are not used by IsoPhase :-)
