### ISSUE TITLE
Bug in GFF output

### ISSUE THREAD

**Issue by nathanhaigh** [Magdoll/cDNA_Cupcake#132]
The GFF output of cupcake looks like this:

```
chr1       PacBio  transcript      95930   98987   .       +       .       gene_id "PB.3"; transcript_id "PB.2.1";
```

At some point the `gene_id` becomes out of sync with the `transcript_id`. In the above case `gene_id` is `PB.3` instead of `PB.2`. In my post-cupcake processing I ended up doing the following to generate valid GFF3:

```
perl -plane 's/gene_id "PB.\d+"; transcript_id "(PB\.\d+)(\.\d+)";/gene_id "$1"; transcript_id "$1$2";/' < all_samples.chained.gff \
  | gawk '$3!="transcript"' \
  | gt gtf_to_gff3 -tidy /dev/stdin \
  | gawk 'BEGIN{FS="\t";OFS="\t"}{if($2=="."){$2="PacBio"} print}' \
  | gff3sort.pl --precise /dev/stdin \
  | bgzip -@ 12 \
> corrected.gff3
```

**Comment by Magdoll** [comment]
Hi @nathanhaigh ,
oops, this looks like a bug that should be easy to fix? Can you tell me the script (or step?) at which the IDs got out of sync? Any test data I can try?
-Liz

**Comment by Magdoll** [comment]
closed unless OP reopens
