### ISSUE TITLE
question about fusion_finder.py

### ISSUE THREAD

**Issue by defendant602** [Magdoll/cDNA_Cupcake#135]
Hi , Liz

        I have a little question about the output file of fusion_finder.py. In file prefix.position,txt, is the fusion part before the connecting symbol '+' always the 5' part of the fusion transcript, and is the part after the '+' symbol always the 3' part of this fusion transcript? 

        Looking forward to your reply, Thanks!

**Comment by Magdoll** [comment]
Hi @defendant602 , it is not - and I'm actually fixing that part in `fusion_finder.py` now. Should have the new version up in a few days.
-Liz

**Comment by defendant602** [comment]
Thanks for your reply and thank you for the efforts you've done in maintaining cDNA_cupcake and SQANTI2!

**Comment by Magdoll** [comment]
Hi @defendant602 ,
Significant improvements have been made to `fusion_finder.py`, as well as improving the [fusion finding tutorial](https://github.com/Magdoll/cDNA_Cupcake/wiki/Best-practice-for-fusion-transcript-finding) to combine it with SQANTI3 + downstream filtering step to  get the candidates.

The fusion output are now given in transcribed order (ex: if the fusion transcript is geneA --> geneB, that is how it'll be listed, and PBfusion.X.1 will be geneA and PBfusion.X.2 will be geneB).

Please update to Cupcake v14.0.0 and let me know if you run into any issues.

-Liz

**Comment by defendant602** [comment]
I got a KeyError when running fusion_collate_info.py, looks like the reason is I didn't have abundance file.

my command is :
`fusion_collate_info.py fusion fusion_classification.txt refAnnotation_fusion.genePred --genome human.fa`

and the KeyError "KeyError: 'PBfusion.5'" occurred in line 170 of fusion_collate_info.py 
`'SpanningReads': count_d[pbid],`

Is the abundance file necessary for running this script?

Thanks!

**Comment by Magdoll** [comment]
Hi @defendant602 , ah, yes! The abundance.txt file is required right now.

I'm making a few minor adjustments to `fusion_collate_info.py` today and tomorrow - I'll update when a new version is up that won't require abundance.
-Liz

**Comment by Magdoll** [comment]
Hi @defendant602 ,
Cupcake v15.1.0 will now work without .abundance.txt file.
Note however without the FL counts, there's going to be a lot of fusion candidates that are not filtered.
-Liz
