### ISSUE TITLE
collapse_isoforms_by_sam.py not found in any bin

### ISSUE THREAD

**Issue by stanleyroche** [Magdoll/cDNA_Cupcake#137]
I have downloaded all the packages I need and I am using anaCogent. After I do 
git clone https://github.com/Magdoll/cDNA_Cupcake.git, 
I try to use 
(anaCogent)$ which collapse_isoforms_by_sam.py  
but there is an error saying:
/usr/bin/which: no collapse_isoforms_by_sam.py in (/home/hos28/miniconda3/envs/anaCogent/bin:/home/hos28/miniconda3/condabin:

**Comment by Magdoll** [comment]
Hi @stanleyroche ,
Please follow the install directions at [Cupcake install wiki](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#install).

You will need to invoke the anaconda environment then do

```
python setup.py build
python setup.py install
```

**Comment by stanleyroche** [comment]
Hello again, when I tried to build an error appeared that is most likely related to the server I am using so I will be resolving that with someone else. I will get back to you once I resolve that.

**Comment by stanleyroche** [comment]
When I used python setup.py build, I am getting this error:
ImportError: dynamic module does not define module export function (PyInit_Scanning)

**Comment by Magdoll** [comment]
Hi @stanleyroche ,

Some [googling](https://stackoverflow.com/questions/36723206/cython-compilation-error-dynamic-module-does-not-define-module-export-function) shows that maybe it's becuz you are not using Python 3?

-Liz

**Comment by stanleyroche** [comment]
I have also tried with using python3 and I am getting the same error message

**Comment by mhsieh** [comment]
Can you tell us the result `type python` command before you run `python setup.py` ?
Is the result is not python from your conda environment, you might want to fix it first.

--
Mengjuei Hsieh 
  Manager, Software Deployment & Test
  Email: mhsieh@pacb.com
  Pacific Biosciences | 1305 O’Brien Drive, Menlo Park, CA 94025

**Comment by stanleyroche** [comment]
When I use type python3, I get /usr/bin/python3.
When I use type python, I get /sc1/apps/spack/v0.5.0/opt/spack/linux-centos7-x86_64/gcc-5.4.0/python-2.7.13-n4a73xpatvwmidf2ogwr4lpx7l2a3tlu/bin/python

**Comment by mhsieh** [comment]
Hi Stanley, none of this looks like anaconda python.
Best,--mj

**Comment by stanleyroche** [comment]
Ok, I will work with my IT to set up anaconda python and will get back to you soon

**Comment by Magdoll** [comment]
Closed unless otherwise noted by OP.
