### ISSUE TITLE
How to get the FASTA phased genomes from the summarized VCF file? 

### ISSUE THREAD

**Issue by pailloufat-stack** [Magdoll/cDNA_Cupcake#138]
Hi,

I would like to get the FASTA phased genome files. For that, from a vcf file, I read that the tool `gatk FastaAlternateReferenceMaker` works , but the summarized vcf file obtained with IsoPhase pipeline doesn't match. 

I mean, I get that main message error when I run `gatk FastaAlternateReferenceMaker`  : `The FORMAT field was provided but there is no genotype/sample data, for input source: my_file.vcf` because the summarized vcf file looks like that : 

```
##fileformat=VCFv4.2
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=HQ,Number=2,Type=Integer,Description="Haplotype Quality">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
Super-Scaffold_100001   672149  .       C       T       .       PASS    DP=210;AF=0.51  GT:HQ
Super-Scaffold_100001   862122  .       A       T       .       PASS    DP=305;AF=0.5   GT:HQ
Super-Scaffold_100001   931168  .       C       A       .       PASS    DP=127;AF=0.5   GT:HQ
Super-Scaffold_100001   967240  .       C       T       .       PASS    DP=127;AF=0.5   GT:HQ
```

There is the FORMAT column but there is no associated genotype in my vcf. Any idea ?

**Comment by Magdoll** [comment]
Hi @pailloufat-stack ,
I probably need to populate the genotype/sample field. Let me work on this a bit and will message when it's up on GitHub.

Thanks for bringing this to my attention.
-Liz

**Comment by pailloufat-stack** [comment]
Thanks for the reply. 

No worries about that. I just noticed there is the genotype/sample field for the vcf files for each loci in the folder `by_loci ` , but not for the summarized vcf file.

Best,
Paillou

**Comment by Magdoll** [comment]
oh right. does this mean you have what you need?

**Comment by pailloufat-stack** [comment]
Not really. I would like to get only one summarized vcf file with all the loci , to run that file  with `gatk` ..

**Comment by Magdoll** [comment]
Hi @pailloufat-stack ,
Cupcake v15.0.0 now should have a new 'SAMPLE' column when you call `collect_all_vcf.py`, see details at the [wiki](https://github.com/Magdoll/cDNA_Cupcake/wiki/IsoPhase:-Haplotyping-using-Iso-Seq-data#out)

Let me know if this works for you!
-Liz

**Comment by pailloufat-stack** [comment]
That's it, thanks Liz.

Paillou

**Comment by Magdoll** [comment]
hi @pailloufat-stack great!
