### ISSUE TITLE
Unrecognized id format m64065_201020_094110 in test.collapsed.group.txt!

### ISSUE THREAD

**Issue by DongnaMa** [Magdoll/cDNA_Cupcake#139]
Hi Magdoll,
when i ran get_abundance_post_collapse.py test.collapsed cluster_report.csv, I have that error message :

Exception: Unrecognized id format m64065_201020_094110 in TGY.collapsed.group.txt!

Can you give me some advice?

Bests,

Luffy

**Comment by Magdoll** [comment]
Hi @DongnaMa ,
Can you show me the first few lines in 

`TGY.collapsed.group.txt`
and
`cluster_report.csv`?

The expected ID format should be something like

`m64065_201020_094110/123452/ccs`

**Comment by DongnaMa** [comment]
Thank you for your timely response, two files below

TGY.collapsed.group.txt:
PB.1.1  m64065_201020_094110/149620146/ccs
PB.1.2  m64065_201020_094110/154011250/ccs
PB.2.1  m64065_201020_094110/151062945/ccs
PB.3.1  m64065_201020_094110/102957595/ccs
PB.4.1  m64065_201020_094110/26935761/ccs

cluster_report.csv:
cluster_id,read_id,read_type
transcript/0,m64065_201020_094110/19203559/ccs,FL
transcript/0,m64065_201020_094110/130483820/ccs,FL
transcript/1,m64065_201020_094110/96928595/ccs,FL
transcript/1,m64065_201020_094110/126289202/ccs,FL
transcript/2,m64065_201020_094110/116589698/ccs,FL

**Comment by Magdoll** [comment]
Hi @DongnaMa ,
I see the issue here. You are supposed to align the file `hq_transcript.fasta` which would have ids such as `transcript/0`, `transcript/1` after running `isoseq3 cluster`. Instead you likely mistakenly aligned and collapsed `flnc.fasta`.

Can you please align + collapse HQ transcript and run this again?

**Comment by DongnaMa** [comment]
Hi @Magdoll ,
Thank you very much. I rerun align + collapse HQ transcript, and my problem is solved.
