### ISSUE TITLE
Getting association file from the Isoseq3 pipeline and from your pipeline.

### ISSUE THREAD

**Issue by pailloufat-stack** [Magdoll/cDNA_Cupcake#142]
Hi Liz,

I was wondering how to get the `cluster_report.csv` file you showed to run the script `get_abundance_post_collapse.py` ? 

Also, to get the association_file and the GFF file, we first need to align the clustered isoforms on the reference genome. I found two ways to do that : 
- with the command you show :  `minimap2 -ax splice -t 16 -uf --secondary=no -C5 myref.fa  clustered.hq.fastq > hq_isoforms.fastq.sam`

- with the Isoseq3 pipeline :  `pbmm2 align clustered.hq.bam myref.fa my_alignment_sorted.bam --preset ISOSEQ --sort `

I know both way rely on the minimap2 algorithm. But will there be a difference with the output vcf file , if I use one rather than the other ? 

Best,
Paillou

**Comment by Magdoll** [comment]
Hi @pailloufat-stack ,

The `cluster_report.csv` should be part of the output from running `isoseq3 cluster`. [see IsoSeq(3) doc here](https://github.com/PacificBiosciences/IsoSeq/blob/master/isoseq-clustering.md#step-4---clustering)

Did you run `isoseq3 cluster`?

-Liz

**Comment by pailloufat-stack** [comment]
Hi Liz,

Yes I did, and I finally found that file. Thanks.

About my other question concerning `pbmm2 align` or `minimap2` ,  I tried both of them. I got 95.636 sequences with `minimap2 `and 95.007 sequences with `pbmm2 align`  . Does this difference come from the fact I used `--secondary=no` with minimap2 , which implies that there is not a secondary alignment, and so, more sequences? 

Paillou

**Comment by Magdoll** [comment]
@pailloufat-stack ,
when you run pbmm2 align for Iso-Seq please use the preset `ISOSEQ`. There are other parameter differences as well. 

```
Alignment modes of --preset:
    SUBREAD     : -k 19 -w 10    -o 5 -O 56 -e 4 -E 1 -A 2 -B 5 -z 400 -Z 50  -r 2000   -L 0.5 -g 5000
    CCS or HiFi : -k 19 -w 10 -u -o 5 -O 56 -e 4 -E 1 -A 2 -B 5 -z 400 -Z 50  -r 2000   -L 0.5 -g 5000
    ISOSEQ      : -k 15 -w 5  -u -o 2 -O 32 -e 1 -E 0 -A 1 -B 2 -z 200 -Z 100 -r 200000 -L 0.5 -g 2000 -C 5 -G 200000
    UNROLLED    : -k 15 -w 15    -o 2 -O 32 -e 1 -E 0 -A 1 -B 2 -z 200 -Z 100 -r 2000   -L 0.5 -g 10000
```

**Comment by Magdoll** [comment]
closed unless OP reopens
