### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ksahlin** [Magdoll/cDNA_Cupcake#143]
Hi Liz,

I want to start using cupcake scripts and I read on `https://github.com/Magdoll/cDNA_Cupcake/` that 
"Since most of the scripts are independent (do not depend on each other), you can either clone the whole directory, or, if you are only interested in a specific script, just download that specific script to your local drive.". 

However, on `https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#install` it says "Unlike most of the other scripts in Cupcake (where you can just use it by directly copying the script or adding it to PYTHONPATH), using Cupcake does require installation.".

Which one is more up to date? 

Also (although you may not have tested) do you _think_ the cupcake scripts will work for python >= v3.7 or only for v3.7? I'm considering integrating it in a conda analysis-environment using python  v3.9? 

Best,
Kristoffer

**Comment by Magdoll** [comment]
Hi @ksahlin ,

both advice is up to date ;)
If you want to use any of the scripts described in https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#install, you need to install.

If you ONLY want to use scripts outside https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#install, you do not need to install.

Does that make sense?

I've only tested Py3.7 but I imagine Py3.9 would work too? The nasty parts may come in other places like numpy and networkx versions though, but Cupcake doesn't use either.
-Liz

**Comment by ksahlin** [comment]
Oh okay, makes sense :)

Alright, then I'll go ahead and try with py3.9.

Thanks!
