### ISSUE TITLE
Does it make sense to change the coverage (X40) to run the select_loci_to_phase.py script?

### ISSUE THREAD

**Issue by pailloufat-stack** [Magdoll/cDNA_Cupcake#145]
Hi Magdoll,

I have two questions, about the default coverage to run the select_loci_to_phase.py script :
- how did you determine that coverage? I mean, it is a pretty high coverage , right?
- and I only got few loci to phase with that coverage, I tried to reduce it at 20X and I got ~3 times more loci to phase. It looks logic, but does it make sense to reduce that coverage ?

Best,
paillou

**Comment by Magdoll** [comment]
Hi @pailloufat-stack ,

You need about 40X coverage to get a p-value of < 0.01 for SNP calling.

So, if you use 30X coverage, you will get more loci to run IsoPhase, but you probably want to adjust the `--pval_cutoff` to a higher p-value, like say 0.05. 

It's mostly a matter of trading off between sensitivity and specificity in SNP calls.

Does that make sense?
-Liz

**Comment by pailloufat-stack** [comment]
Thanks for the reply.

That makes sense, right. About the parameter `--pval_cutoff` , I can't find it. Is it a `samtools mpileup` paramater?

**Comment by Magdoll** [comment]
Hi @pailloufat-stack oops forgot to mention it is in `run_phaser.py`.
 So you want to modify the file when you are making a run-specific bash script as [talked about here](https://github.com/Magdoll/cDNA_Cupcake/wiki/IsoPhase:-Haplotyping-using-Iso-Seq-data#generate-and-run-isophase-commands)

Modify the lines in `run_phasing_in_dir.sh` that calls `run_phaser.py` so now it uses a diff p-val other than default

-Liz
