### ISSUE TITLE
abundance script: `pbid` field set to `NA`. Ignoring this read.

### ISSUE THREAD

**Issue by jodithea** [Magdoll/cDNA_Cupcake#146]
Hi,

I am running the get_abundance_post_collapse.py script and received warnings: 'WARNING: isoseq3 format detected. Output `length` column will be `NA`.' (1905402 lines of this warning). I understand this warning is not a problem (issue #42: https://github.com/Magdoll/cDNA_Cupcake/issues/42). However, I also receive this message:

'sequence m64150_201031_012853/119539452/ccs has `pbid` field set to `NA`. Ignoring this read.'

I get this message for 36709 lines (different sequences).  The outputs *.collapsed.read_stat.txt and *.collapsed.abundance.txt look fine. I just wanted to check whether this message is a problem (will my outputs be missing reads?) or can I ignore it?

Thank you for your help!
Jodi

**Comment by Magdoll** [comment]
Hi - this warning is not an issue. I should probably remove it since this is always going to bee the case with the way isoseq3 formats output.

**Comment by jodithea** [comment]
Thank you so much for the quick reply!

**Comment by B10inform** [comment]
Hi, 

With the test files i am getting. I tried output from "collapse_isoforms_by_sam.py --input hq_isoforms.fastq --fq \
   -s hq_isoforms.fastq.sorted.sam --dun-merge-5-shorter -o test". I get the same error.

get_abundance_post_collapse.py test.collapsed cluster_report.csv
 
"sequence m64012_190727_053041/82905133/ccs has `pbid` field set to `NA`. Ignoring this read." error. 

**.collapsed.read_stat.txt is:**
id	is_fl	stat	pbid
m64012_190727_053041/105120134/ccs	Y	unmapped	NA
m64012_190727_053041/21628950/ccs	Y	unmapped	NA

**The collapsed abundance,txt is empty:**
#
# -----------------
# Field explanation
# -----------------
# count_fl: Number of associated FL reads
# norm_fl: count_fl / total number of FL reads, mapped or unmapped
# Total Number of FL reads: 0
#
pbid	count_fl	norm_fl

Any help would be really appriciated.

Thanks
