### ISSUE TITLE
'cupcake==8.7.4'

### ISSUE THREAD

**Issue by LeontienM** [Magdoll/cDNA_Cupcake#147]
I wanted to do the collapse_isoforms_by_sam.py by the cupcake software but this error comes up everytime 

pkg_resources.DistributionNotFound: The 'cupcake==8.7.4' distribution was not found and is required by the application.

I already updated the cupcake by this -->   git clone https://github.com/Magdoll/cDNA_Cupcake.git
And my python version is 3.7.5 
and still it won't work...

Can someone help me?

Leontien M.

**Comment by Magdoll** [comment]
Hi @LeontienM did you follow the [install](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#install) directions listed here?

If problems still persists plz list the entire set  of commands (including install + calling collapse script) and the error here

-Liz
