### ISSUE TITLE
Low mapping rates when using the recommended parameters for STARlong and GMAP

### ISSUE THREAD

**Issue by bam2wigKillMe** [Magdoll/cDNA_Cupcake#149]
Hello,
I'm trying to align isoseq sequencing data to genome, but when I use  the recommended parameters for STARlong and GMAP from here: [https://github.com/Magdoll/cDNA_Cupcake/wiki/Best-practice-for-aligning-Iso-Seq-to-reference-genome:-minimap2,-deSALT,-GMAP,-STAR,-BLAT](url)

I got 99.98% reads unmapped because of too short when using STAR, and 88.9% unmapped when using GMAP.
But actually the isoseq reads I polished got average length 4327nt.
I cannot figure out why, could you please give me a hint or a website where I may find it out.

Thank you for your attention,
Best wishes!

**Comment by Magdoll** [comment]
Hi @bam2wigKillMe ,
This page probably needs some updating. That said, can you please try minimap2 and report the mapping results?
-Liz

**Comment by bam2wigKillMe** [comment]
Thank you for your answer very much, later I found that I mapped reads to wrong genome.
Sorry for your time, I will be more careful before asking.
Best!
