### ISSUE TITLE
Better to stay with the isoseq3 collapsing step or add a collapsing step with collapse_isoforms_by_sam.py ?

### ISSUE THREAD

**Issue by Pailloufat** [Magdoll/cDNA_Cupcake#153]
Hi  @Magdoll, 

I'll use your script about finding fusion genes, thanks for that ! 

You say : "It is strongly recommended to collapse sequences into unique transcripts BEFORE running SQANTI3 using cDNA_Cupcake or TAMA." (https://github.com/ConesaLab/SQANTI3) .

You mean the final hq isoforms obtained with the `isoseq3 cluster` are not enough clustered? So, we should use the script `collapse_isoforms_by_sam.py` (on the mapped hq isoforms with minimap2 on the reference) ?

Bests,

**Comment by Magdoll** [comment]
Hi @Pailloufat ,
Yes , I recommend after runnning `isoseq3 cluster` to get the HQ transcripts that you further map it, collapse it with [Cupcake](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#collapse) or TAMA to get a set of unique transcripts as a GFF file. Then give that GFF file as input to SQANTI3.


The mapping + collapse will further remove poorly or unmapped transcripts, you get full control over which aligner (minimap2, STAR, gmap) you want to use, what parameters to use, etc. So you know the GFF you are giving to SQANTI3 is what you intend to.

-Liz

**Comment by Pailloufat** [comment]
Would you better suggest running `collapse_isoforms_by_sam.py` or `fusion_finder.py` ? As I understand, the main difference between both is `collapse_isoforms_by_sam.py` ignores chimeric transcripts.

**Comment by Pailloufat** [comment]
Ok, it is a collapsing of collapsing hq isoforms ;) ! And so, I will give to SQANTI3 the `test.collapsed.gff` file from the `collapse_isoforms_by_sam.py` output.

Because the `collapse_isoforms_by_sam.py` and `fusion_finder.py` do (almost) the same thing, right? It is just a question of ignored chimeric transcripts?

**Comment by Magdoll** [comment]
Hi @Pailloufat ,
that is correct. basically the collapse and fusion script take the same aligned SAM input. the former ignores the fusions (by nature of asking a single alignment to have sufficient coverage) and the latter specifically look for chimeric alignments
