### ISSUE TITLE
Collapse isoforms using large amount of RAM

### ISSUE THREAD

**Issue by sid-sethi** [Magdoll/cDNA_Cupcake#154]
Hi,

We want to run collapse isoforms on a SAM file obtained by mapping nanopore reads to the human genome. We tested collapse_isoforms on a SAM file of one chromosome (12 GB in size). We have noticed that the RAM usage of the process goes up to ~500g - which is quite a lot for our server. We are wondering if this is normal for this algorithm or are we doing something wrong on our side?

Regards,
Sid

**Comment by Magdoll** [comment]
hi @sid-sethi  it is possible. I'm working on a new version of collapse that will parallelize the process and also use a BAM file instead which may reduce the footprint. PLease stay tuned for a new Cupcake release (likely to be labeled v25)

**Comment by RyanYip-Kat** [comment]
I also meet this problem

**Comment by Magdoll** [comment]
Hi @RyanYip-Kat ,

I am testing a new parallelized version of Cupcake which probably will make it faster - but not super clear on RAM usage yet. 

If you'd like to give it a try it is at the `collapse_dev` branch:
https://github.com/Magdoll/cDNA_Cupcake/tree/collapse_dev

```
$  collapse_isoforms_by_sam.py -h
usage: collapse_isoforms_by_sam.py [-h] [--input INPUT] [--fq] [-s SAM]
                                   [-b BAM] -o PREFIX [-c MIN_ALN_COVERAGE]
                                   [-i MIN_ALN_IDENTITY]
                                   [--max_fuzzy_junction MAX_FUZZY_JUNCTION]
                                   [--max_5_diff MAX_5_DIFF]
                                   [--max_3_diff MAX_3_DIFF]
                                   [--flnc_coverage FLNC_COVERAGE]
                                   [--gen_mol_count] [--dun-merge-5-shorter]
                                   [--cpus CPUS]
```

you can now provide aligned, sorted BAM files as input
(the use of --sam or --bam are mutually exclusive)
you can also optionally skip --input
so a simple use would be

```
collapse_isoforms_by_sam.py -b aligned.bam -o test.out --cpus 4
```

if you decide to try this let me know how it goes!
Thanks,
-Liz
