### ISSUE TITLE
collapse_isoforms_by_sam.py - BAM only input

### ISSUE THREAD

**Issue by jackhump** [Magdoll/cDNA_Cupcake#155]
Hi Liz,

I'm trying to get rid of IsoSeq collapse and just run Cupcake directly on the FLNC BAM files, once they have been aligned.

Is it possible to have just that file as input, rather than requiring a separate FASTA/FASTQ?

**Comment by jackhump** [comment]
...and now I remembered that currently you only take SAM files as the input there.

My FLNC BAM file (30 SMRT cells merged together) is 109GB so I'd prefer not to have to convert to both SAM and FASTA.

**Comment by Magdoll** [comment]
...I hear you.

**Comment by Magdoll** [comment]
In testing!
