### ISSUE TITLE
reads unmapped

### ISSUE THREAD

**Issue by mei-du** [Magdoll/cDNA_Cupcake#156]
Hi team,
I'm trying to collapse ONT reads to use with SQANTI3. I edited the read names to make them more PacBio-like and have mapped them with minimap2, then sorted the .sam file according to your wiki instructions. I was able to run `collapse_isoforms_by_sam.py` but `merged_sub_edited.ignored_ids.txt` is huge and is saying that (most) reads are unmapped. Could you provide any clarification? I've provided the start of my sorted sam and the ignored_ids below. Thanks

barcode01/100021	4	*	0	0	*	*	0	0	ATTTTTTTTTTTTTTTCTTCTCTTCCCTTCGTCTTTTCCTTTCTACTACTTCTTTCTACTCTCTGATTCTTTTCTCTTTCTTCTCTTTCTTGCTTCTCCTTTTGAGCTGTCATCACGATCCAGGTTCTTCACCCAGCAGCCCTC	%./22223333333332796@2::,64;044;:<=:33((()($$##$))'($,,,'%/2/(*$%$.-/4997)$33774;'6?:AAE9=>>:=?<9:532/*&%#$$&+-/4<257@>=:.37&:=@D@8761&%&'')+-55	rl:i:16
barcode01/100022	4	*	0	0	*	*	0	0	GTGAACCTGATAAGCGAAAGCGAAAAGCTCCTGCACTCTGAAGCTGGAAATAAAGCGAAAACTTTAAGGCCGAAGGCGGTGTTGAAAGATTATTACGTACGAAAGAAGAAGATCGCGTCACCACCTTCGCGGCGACAAGAAGACACGACTCCAGAGGGTGACTAATATCGGAAGAAGCGCTCCCCGGGAAACGGCTTGGAAGCCGCTATTATATATGTCAGGTTTCACGCTGTTGCGGTCTTGCCGAAGATGAGGAACTTAGCAGCTGCGCCATTCGTTGTGGATATGTTAAGCCGCTCAAGCACCAGATTAAACAGGCTGTGGCTATGTGACGACCCAGACCTTCGGGTCAACGCCTGATTCGGCTGATTGAAGAAGAAACATATGTTCGACGAAAACCAGTTAAAGTCTTTGGATGTGCTCTTCGTGCCAAGTCATCTAACTGGAATCAACTGCTAATTCCTGGATAACAACTGACAACATGTCTTTACGCGGCAGAAGACAGAGCAACGAGGAGCAAGTCTGAAAACCTGACTCAACTTTCTTGTCA	$$%%'&$%$$%%%$#$&&'($&&&'*%.//-.(-$--*%&%%'$%'&)*%%()(%%&'%''&''($%'$##$)(*-..47557211-*$%'%%&$#$$%&*,.*(,,(.+)'0+&&%'%#%%$%$$$%$#$$$'&'%%).,+)+'%$&#$''%%'%&%#$$$$&($$&0,,*(%$'()*25;52,&(*&%%#%%#$$$)$,%&$$#%%$&$$&#''&+)&)1/6-'$&&%'&$%$#%%+%%'$#$$%&&&(()&&&,$$$$"$%####$$###$%&'()%$(+(&(($%&$%&(&$&(*'&*)))*('&&'&('$$%...,'&''%$&&%'%*,*((''$&%%%%#$&8::8623989=:<;*,+(')).0++*+1.%('&-04;44;<:)$#)679435)+31,()$(#$$'*/.,&$$$%%"%%%-'##%$066552)''*,+')$.)$#%(%..-09:1.135+%,%$''$%&%%&$$%&&)***($#$$%%$&*$$$$$$$($$$##$$%&%,--*&-)%%('&$#%%$$#%$$$#$%6387553$	rl:i:0
barcode01/10002	4	*	0	0	*	*	0	0	TGGGGAGCCCATTGCTGGCTCCGGCCGGTTACGCAGCCCTCGGACCCCCAGGGTAGGCGAGGGTTCGAGGGCTGAAGTTCGGGGGCCAACCTGGTCCACGTGGGTAAA	40-,*$/,,+),-%")+6+;<<368:+034+-.--&237;=043*,*)&'.58459>%'')-79830*%(*&$))(8EDB*()'9?AB4=ACC;A>?10-767212(%rl:i:0
barcode01/100024	4	*	0	0	*	*	0	0	TGGGGGAGCCATTGTGGCTCCGGCCGGTTGAGCCCTCGGACCCTCAGGGTAGGCGGGTTTGAGGGCTGAAGTTCGAGGCCAACCTGGTCACATGGGTTAAAAAAAAAAAAAAAAAAAA	,+-+++).9:8:;0-*'%&12*/11')&(-+-776;;27=/0,:;-6-,((,2--'<=<.,-+)*$$&&&+??B/'/3'';59<>?8;>,01/./6;<?A>52//,,.002//./,+%	rl:i:23
barcode01/100034	4	*	0	0	*	*	0	0	CTTTTTTTTTTTTTTTTTTTAGCCCACGTGGACCAGGTTGGCCTCCGACTCGTGCCCTCGACCTCGCCTACCCTGAGGGTCGAGGGCCCTATTTCGGCCGGAGCCACAATGGCTCCCCCA	652.-,+*)**++++)('&$$&*-248<@A<A;B==:890:9736/'(*.-+3.5937+%'./7<>>?@;<<990&+0;933*/.4241/%&'*1*,-.')&077%5;=77:;;D>8?=9	rl:i:22

```
barcode01/100021	Unmapped.
barcode01/100022	Unmapped.
barcode01/10002	Unmapped.
barcode01/100024	Unmapped.
barcode01/100034	Unmapped.
barcode01/100036	Unmapped.
barcode01/100046	Unmapped.
barcode01/100048	Unmapped.
barcode01/100055	Unmapped.
barcode01/100059	Unmapped.
```

**Comment by Magdoll** [comment]
Hi @mei-du ,
The reads are unmapped. The [3rd column in a SAM file](https://samtools.github.io/hts-specs/SAMv1.pdf) is the reference(chromosome) name if it is mapped and `*` if it is not. All the examples you showed me are unmapped, so probably something wrong with the mapping process.
