### ISSUE TITLE
collapse_isoforms_by_sam.py throws duplicate ID error when input is compressed

### ISSUE THREAD

**Issue by Adamtaranto** [Magdoll/cDNA_Cupcake#159]
Hi Liz, 

I've found that _collapse_isoforms_by_sam.py_ throws a confusing error if the transcripts that were aligned with Minimap2 etc are gzipped. See below. Would it be possible to have the tool take compressed reads as input so that they don't need to be unzipped/rezipped by the user?

`collapse_isoforms_by_sam.py --input flnc.fasta.gz -s PREFIX.fastq.sorted.sam --dun-merge-5-shorter -o PREFIX.flnc
`

```
Traceback (most recent call last):
  File "/share/.conda/envs/annotation/bin/collapse_isoforms_by_sam.py", line 245, in <module>
    main(args)
  File "/share/.conda/envs/annotation/bin/collapse_isoforms_by_sam.py", line 169, in main
    check_ids_unique(args.input, is_fq=args.fq)
  File "/share/.conda/envs/annotation/lib/python3.8/site-packages/cupcake/tofu/utils.py", line 13, in check_ids_unique
    raise Exception("Duplicate id {0} detected. Abort!".format(r.id))
Exception: Duplicate id  detected. Abort!
```

**Comment by Magdoll** [comment]
Hi @Adamtaranto ,
Right now collapse doesn't accept gzipped input (the latest version however will accept a aligned, sorted BAM input via `--bam` and you can skip `--input`).

If this problem persists after you unzipped the input flnc.fasta, plz let me know by reopening the ticket.
-liz
