### ISSUE TITLE
file format wrong

### ISSUE THREAD

**Issue by hmyh1202** [Magdoll/cDNA_Cupcake#16]
File "/cupcake/tofu/compare_junctions.py", line 21, in compare_junctions
    strand = r1.strand
AttributeError: GMAPSAMRecord instance has no attribute 'strand'

**Comment by Magdoll** [comment]
Hi,

Please give me the full set of commands you are running.

**Comment by hmyh1202** [comment]
My code is：
python fusion_finder.py \
  --input sample.hq.fastq \
  --fq \
  --sam gmap.sort.sam \
  --prefix sample \
  --min_locus_coverage 0.1 \
  --min_total_coverage 0.99 \
  --min_dist_between_loci 100000
  --cluster_report_csv report.csv

It should be related to sam file format. When I run alignment using GMAP I did not use "-n 0 -z sense_force ".  Now is OK.

**Comment by Magdoll** [comment]
OK thanks.

**Comment by hmyh1202** [comment]
Recentlly I have got the same problem, hard to read the fusion_finder.py

**Comment by hmyh1202** [comment]
Traceback (most recent call last):
  File "Python-2.7.8/bin/fusion_finder.py", line 393, in <module>
    min_dist_between_loci=args.min_dist_between_loci)
  File "Python-2.7.8/bin/fusion_finder.py", line 301, in fusion_main
    o = merge_fusion_exons(v, max_fusion_point_dist=100, max_exon_end_dist=0, allow_extra_5_exons=allow_extra_5_exons)
  File "fusion_finder.py", line 207, in merge_fusion_exons
    if all(is_fusion_compatible(r1, r2, max_fusion_point_dist, max_exon_end_dist, allow_extra_5_exons) for r2 in r2s):
  File "fusion_finder.py", line 207, in <genexpr>
    if all(is_fusion_compatible(r1, r2, max_fusion_point_dist, max_exon_end_dist, allow_extra_5_exons) for r2 in r2s):
  File "Python-2.7.8/bin/fusion_finder.py", line 153, in is_fusion_compatible
    type = compare_junctions(r1, r2)
  File:/Python-2.7.8/lib/python2.7/site-packages/cupcake/tofu/compare_junctions.py", line 21, in compare_junctions
    strand = r1.strand
AttributeError: GMAPSAMRecord instance has no attribute 'strand'

**Comment by hmyh1202** [comment]
Alignment  para
bin/gmap -D /home/share/gmap_db/ -d hg38 -f samse -n 0 -t 12 -z sense_force  hq_isoforms.fastq

**Comment by hmyh1202** [comment]
May be the issue of 'strand = r1.strand' in compare_junctions.py

strand = r1.flag.strand

**Comment by Magdoll** [comment]
Hi,
I have fixed this issue. Please update to the latest commit in Cupcake (version 3.6, commit [9848e783978cc48e39d8f5220ef824c86c8df874](https://github.com/Magdoll/cDNA_Cupcake/commit/9848e783978cc48e39d8f5220ef824c86c8df874)).

You can verify that you have the same commit in your repo by 

```
$ git rev-parse HEAD
9848e783978cc48e39d8f5220ef824c86c8df874
```


Let me know if this fixes the problem.
Thanks!
--Liz
