### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by ouyang-lang** [Magdoll/cDNA_Cupcake#161]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

my command:
collapse_isoforms_by_sam.py --input full_length_output.fq --fq -s full_length_sorted.bam --dun-merge-5-shorter -o test -c 0.9 -i 0.85

My bam file is compared with minimap2

Display decoding error, I am not sure why

**Comment by agansama** [comment]
perhaps this command need input a 'sam' file instead of a 'bam' file.
You can have a try.

**Comment by Magdoll** [comment]
Correct. Use `--bam` if it's a sorted bam. `-s` expects a sorted SAM
