### ISSUE TITLE
How to merge two PACBIO collapsed files into one comprehensive database

### ISSUE THREAD

**Issue by Huangyizhong** [Magdoll/cDNA_Cupcake#165]
Hi, there 
 Thanks for the cDNA_Cupcake to deal with PACBIO data. I have 10 samples PACBIO data, and following the Iso-Seq protocol and also use the illumina data to correct it. Using the GMAP to align the PACBIO data to the genome. Finally, get the collapsed file for each tissues. I wan to ask how to merge the 10 collapsed file into a comprehensive transcripts database? Is  there some scripts? Thanks so much.  Another question, look at the picture attached, how does the red arrow indicates isoforms comes out?
![image](https://user-images.githubusercontent.com/31943359/123291809-0b102800-d545-11eb-9d00-a43cadc16f2f.png)
  
Sincerely 
Yizhong Huang

**Comment by Magdoll** [comment]
Hi @Huangyizhong ,

You can merge samples with [chaining in Cupcake](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#chain) or [TAMA merge](https://github.com/GenomeRIK/tama/wiki/Tama-Merge).

The red arrow seems to point to a much longer isoform...?

-Liz
