### ISSUE TITLE
cupcake dev bam input

### ISSUE THREAD

**Issue by mei-du** [Magdoll/cDNA_Cupcake#166]
Hi,
I'm trying out using a bam input with cupcake_dev as suggested in #154 as I was also experiencing problems with huge amounts of RAM. I've sorted the bam as per the usual cupcake sort command, but am receiving this error 
![image](https://user-images.githubusercontent.com/58542302/125178496-d54b8e80-e228-11eb-8a56-2ce97a6790ea.png)

I also tried using an input fq and sorted sam as I've done in the past but received this: 
![image](https://user-images.githubusercontent.com/58542302/125178506-09bf4a80-e229-11eb-902f-78c259cc8e15.png)

Could you offer any insight into this? Thanks!

**Comment by Magdoll** [comment]
Looks like it's missing the BAM file header. What did you use to get the BAM file? What were the commands?

**Comment by mei-du** [comment]
samtools view -bS sam > bam
sort -k 3,3 -k 4,4n bam > sorted_bam

**Comment by Magdoll** [comment]
Hi @mei-du 

I don't think you can sort a bam file with `sort`.

Please try

```
samtools view -bS file.sam > file.bam
samtools sort file.bam > file.sorted.bam
samtools index file.sorted.bam
```

**Comment by mei-du** [comment]
Hi @Magdoll,
That worked, and the dev version works great, thank you so much!!! The multi-threading is actually a lifesaver. I just noticed this small typo but it doesn't affect merging.
![Screen Shot 2021-08-06 at 12 01 37](https://user-images.githubusercontent.com/58542302/128948258-655a052b-fe28-470a-914c-ee7b80424705.png)
