### ISSUE TITLE
Workflow for haplotype tagged bam in IsoPhase result

### ISSUE THREAD

**Issue by baozg** [Magdoll/cDNA_Cupcake#168]
Hi, Eliz

In the medium post (https://medium.com/@Magdoll/decoding-a-coastal-giant-full-length-transcriptome-of-sequoia-sempervirens-87e3f924bfe8), the readwood Iso-Seq reads have colored and grouped by their haplotype. How did it done with the IsoPhase result? 
I try use the hap_postclean `phased.nopartial.cleaned.hap_info.txt` to add a tag in the aligned bam, but IGV did not show the same snapshot.

Would you mind share the workflow for this snapshot? 

![image](https://user-images.githubusercontent.com/20680150/128462650-7647b398-22e6-437a-be8d-ba4533727087.png)

**Comment by Magdoll** [comment]
Hi @baozg , you're right - I had an extra python script that colored it into tagged BAM files! I'll put that script up hopefully in the next few days and let you know!
-Liz

**Comment by baozg** [comment]
Hi, @Magdoll 

Thanks. I have try add haplotype info to sam by myself. 
![image](https://user-images.githubusercontent.com/20680150/128520158-4d3ee1e9-75d1-47de-9c1f-b7eb3ba1e1e3.png)

But yours more like publication-quality. Looking forward the share.


Another question about IsoPhase for phased assembly quality check. 
Are the panel of genome haplotigs from the `minimap2` mapping for `hifiasm` contigs?

**Comment by Magdoll** [comment]
Hi @baozg 

>Are the panel of genome haplotigs from the minimap2 mapping for hifiasm contigs?
Yes that is correct.

**Comment by Magdoll** [comment]
Hi @baozg ,

I've added [tagging for IsoPhase](https://github.com/Magdoll/cDNA_Cupcake/wiki/IsoPhase:-Haplotyping-using-Iso-Seq-data#tag) to Cupcake v26.1.0

Please give it a try.

Thanks!
-Liz
