### ISSUE TITLE
CCS for Targeted Iso Seq QC?

### ISSUE THREAD

**Issue by xiaonalu** [Magdoll/cDNA_Cupcake#172]
Hi,
I am a little confusing about the input for the Targeted Iso Seq QC. Should I directly use the fastq/a of the ccs as the very initial input for this Targeted Iso Seq QC, or I should go through some steps of Isoseq3? Does SQANTI work for Targeted Iso? Thanks
Best
Xiaona

**Comment by Magdoll** [comment]
Hi - 

Yes, SQANTI3 will work for targeted Iso-Seq. 
In terms of analysis, you can either directly analyze full-length (FL) CCS reads after running `isoseq3 refine` or you can additionally run through clustering with `isoseq3 cluster`, but the cluster step might take a while if you are sequencing just one gene.

-Liz
