### ISSUE TITLE
problem using run_preCluster.py

### ISSUE THREAD

**Issue by jcleple33** [Magdoll/cDNA_Cupcake#178]
Hi!

I can't find all the original transcripts in the preclustering groups:

I am using cogent-8.0.0 and minimap2 (2.22-r1101)
starting with 1,402,457 HQ transcripts as  isoseq_flnc.fasta I recover only 1,401,412 transcripts into preclusters(1,296,013)+orphans(21895)+tucked(83502)+chimeras(2) --- so, 1045 were lost along the way.

Please, could you tell me where I am making a mistake? am I missing something?

Many thanks in advance
JC

**Comment by Magdoll** [comment]
sorry, but preCluster is no longer supported. I might leave the code there just a bit longer before fully deprecating it.
