### ISSUE TITLE
MTX appears to have the wrong number of entries

### ISSUE THREAD

**Issue by nsalomonis** [Magdoll/cDNA_Cupcake#183]
Just looking at initial single-cell isoform estimates in the cupcake output sparse matrix data. It was failing with the sparse matrix import in python 
`mat = scipy.io.mmread(matrix_dir`
with 
`ValueError: 'entries' in header is larger than number of entries`

This is easily corrected by editing the .mtx file entry summary (line three) which had the incorrect total number of entries (in this case, the third value was listed as 2464523 but it should be 1423965). 

Checking to see if this is bug in the output or an upstream processing issues elsewhere.

**Comment by Magdoll** [comment]
Hi @nsalomonis , can you describe the command you ran and scipy version? Just wanna make sure we can reproduce / understand the issue source. Thanks!
-Liz

**Comment by Magdoll** [comment]
close unless OP reopens
