### ISSUE TITLE
Script 'scripts/collapse_isoforms_by_sam.py' not found in metadata at '/research/rgs01/home/clusterHome/xchen2/software/cDNA_Cupcake/cupcake.egg-info'

### ISSUE THREAD

**Issue by xiaolongchen0627** [Magdoll/cDNA_Cupcake#184]
I am installing Cupcake step by step as the instruction . 

it was installed successfully ,and 
$ which collapse_isoforms_by_sam.py 
~/.conda/envs/anaCogent/bin/collapse_isoforms_by_sam.py

but when I tried to use the script , it shows the error : 

~/.conda/envs/anaCogent/bin/collapse_isoforms_by_sam.py

Traceback (most recent call last):
  File "/home/xchen2/.conda/envs/anaCogent/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==28.0.0', 'collapse_isoforms_by_sam.py')
  File "/research/rgs01/applications/hpcf/authorized_apps/rhel7_apps/python/install/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/research/rgs01/applications/hpcf/authorized_apps/rhel7_apps/python/install/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1454, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/collapse_isoforms_by_sam.py' not found in metadata at '/research/rgs01/home/clusterHome/xchen2/software/cDNA_Cupcake/cupcake.egg-info'

Could you please help check what can possibily cause this issue ?
Thanks,
Xiaolong.

**Comment by xiaolongchen0627** [comment]
and all the other scripts can not be used because of the same issue.

**Comment by kechalar-hua** [comment]
The same issue.

**Comment by xiaolongchen0627** [comment]
found the solution in https://github.com/Magdoll/cDNA_Cupcake/issues/140

**Comment by LilyLuyang** [comment]
Hello, have you solved this issue? I just encountered the same error with you.
Could you give some prompts for this problem if you have addressed? 

Thanks,
Lily
