### ISSUE TITLE
The question about finding fusion genes

### ISSUE THREAD

**Issue by 2209983424** [Magdoll/cDNA_Cupcake#187]
Why the question that TypeError: '<' not supported between instances of 'NoneType' and 'NoneType' in fusion_finder.py is always appeared.How we can solve it.We are pretty sure that the parameters entered are correct.Thanks.

**Comment by Magdoll** [comment]
Hi,
Is it possible to share the data that caused this error confidentially? I can request a secure file upload.
Thanks,
-liz

**Comment by wuqi21** [comment]
Hi，
I have also encountered the same problem. Can you please resolve the error report？
Thanks.

**Comment by Magdoll** [comment]
Hi @wuqi21 ,
Cupcake support is discontinuing overall - for finding fusion transcripts we now recommend https://github.com/pacificBiosciences/pbfusion which is being actively developed and maintained - please head there and give it a try. Thanks!
-Liz
