### ISSUE TITLE
error while trying to run collapse_isoforms_by_sam.py 

### ISSUE THREAD

**Issue by BeatrizdeToledo** [Magdoll/cDNA_Cupcake#188]
Good afternoon, 
I am an error while trying to run collapse_isoforms_by_sam.py 

python collapse_isoforms_by_sam.py --input hq_transcripts_renamed.fasta  -s highquality_gmap1_sort_cup.sam -o highquality_gmap1_sort_cup                      
Traceback (most recent call last):
  File "collapse_isoforms_by_sam.py", line 30, in <module>
    from cupcake.tofu.utils import check_ids_unique
ModuleNotFoundError: No module named 'cupcake'

I have runned it before with older cupcake versions and it worked

I am running it in my laboratory cluster, so I copy cupcake to my cluster folder, module load apps/python3/3.7.0 and run it. this used to work in previous versions. did something change? 

Thank you 
Beatriz

**Comment by Magdoll** [comment]
You should not be directly calling the collapse script through `python collapse_isoforms_by_sam.py`. You should first [install Cupcake per the instructions](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#install) here. Then you can try something like:

```
which collapse_isoforms_by_sam.py
```

If that works you will know you have successfully installed Cupcake.

Cheers,
-Liz
