### ISSUE TITLE
little typo

### ISSUE THREAD

**Issue by splaisan** [Magdoll/cDNA_Cupcake#189]
https://github.com/Magdoll/cDNA_Cupcake/wiki/Iso-Seq-Single-Cell-Analysis:-Recommended-Analysis-Guidelines#3-detect-umis-and-cell-barcodes

Refer to the isoseq3 tag documentation for the latest usage.

isoseq tag output.5p--3p.fl.bam flt.bam --design T-10U-16B
where the **--design T-8U-12B** indicates a 10bp UMI and 16bp cell barcode between the polyA tail and the 3' cDNA primer.

10/16 rather than 8/12 in the comment below the actual command

**Comment by Magdoll** [comment]
Thank you! Typo fixed.
