### ISSUE TITLE
Chain samples together ('chain_samples.py')

### ISSUE THREAD

**Issue by xogur** [Magdoll/cDNA_Cupcake#22]
Hi,

I am trying to use the 'chain_samples.py'. But, I couldn't find the count file (*.count.txt) for the COUNT_FILENAME in the config file. The '*.count.txt' is not generated by running the 'collapse_isoforms_by_sam.py'. I did try to use the '*.collapsed.abundance.txt' instead of the '*.count.txt' after running the 'get_abundance_post_collapse.py', but I got an error such as "NameError: global name 'count_header' is not defined". I will appreciate it if you let me know how to treat the COUNT_FILENAME in the config file to run the 'chain_samples.py'. Thank you!

Taehee

**Comment by Magdoll** [comment]
Hi @xogur ,

So are you saying `get_abundance_post_collapse.py` did successfully work and you get a `xxxxx.collapsed.abundance.txt`? And just the `chain_samples.py` itself failed?

Would you mind posting the full command for `chain_samples.py` and the error message? Also, the first few lines for `xxxxx.collapsed.abundance.txt` via:

```
$ head -n 15 xxxxx.collapsed.abundance.txt
```

**Comment by xogur** [comment]
Hi Magdoll,

I didn't have any error in the 'get_abundance_post_collapse.py'. 

Please take a look at my log for the 'chain_samples.py' and the 'config' and the 'xxxxx.collapsed.abundance.txt' at below. Thank you!

#log of the 'chain_samples.py'
-sh-3.2$ chain_samples.py test.config norm_nfl
Sanity checking. Retrieving PBIDs from /isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/tofu2/evaluate_tofu2/collapse3/test.collapsed.group.txt,/isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/tofu2/evaluate_tofu2/collapse3/test.collapsed.gff,/isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/tofu2/evaluate_tofu2/collapse3/test.collapsed.abundance.txt...
Sanity checking. Retrieving PBIDs from /isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/smrtanalysis_3/bax2bam/collapse/collapse2/test.collapsed.group.txt,/isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/smrtanalysis_3/bax2bam/collapse/collapse2/test.collapsed.gff,/isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/smrtanalysis_3/bax2bam/collapse/collapse2/test.collapsed.abundance.txt...
Traceback (most recent call last):
  File "/opt2/Python-2.7.13/bin/chain_samples.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==3.9', 'chain_samples.py')
  File "/opt2/Python-2.7.13/lib/python2.7/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt2/Python-2.7.13/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "/opt2/Python-2.7.13/lib/python2.7/site-packages/cupcake-3.9-py2.7-linux-x86_64.egg/EGG-INFO/scripts/chain_samples.py", line 233, in <module>
    chain_samples(sample_dirs, sample_names, group_filename, gff_filename, count_filename, args.field_to_use, args.fuzzy_junction, args.allow_5merge, fastq_filename)
  File "/opt2/Python-2.7.13/lib/python2.7/site-packages/cupcake-3.9-py2.7-linux-x86_64.egg/EGG-INFO/scripts/chain_samples.py", line 121, in chain_samples
    count_info = read_count_info(count_filename, dirs, field_to_use)
  File "/opt2/Python-2.7.13/lib/python2.7/site-packages/cupcake-3.9-py2.7-linux-x86_64.egg/EGG-INFO/scripts/chain_samples.py", line 111, in read_count_info
    return count_header, count_info
NameError: global name 'count_header' is not defined
-sh-3.2$ 

#'config'
SAMPLE=1;/isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/tofu2/evaluate_tofu2/collapse3
SAMPLE=2;/isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/smrtanalysis_3/bax2bam/collapse/collapse2

GROUP_FILENAME=test.collapsed.group.txt
GFF_FILENAME=test.collapsed.gff
COUNT_FILENAME=test.collapsed.abundance.txt
FASTQ_FILENAME=test.collapsed.rep.fq

#'xxxxx.collapsed.abundance.txt'
#
# -----------------
# Field explanation
# -----------------
# count_fl: Number of associated FL reads
# count_nfl: Number of associated FL + unique nFL reads
# count_nfl_amb: Number of associated FL + unique nFL + weighted ambiguous nFL reads
# norm_fl: count_fl / total number of FL reads
# norm_nfl: count_nfl / total number of FL + unique nFL reads
# norm_nfl_amb: count_nfl_amb / total number of all reads
# Total Number of FL reads: 17033
# Total Number of FL + unique nFL reads: 20533
# Total Number of all reads: 21143
#
pbid	count_fl	count_nfl	count_nfl_amb	norm_fl	norm_nfl	norm_nfl_amb
PB.1.1	2	2	2	1.1742e-04	9.7404e-05	9.4594e-05
PB.2.1	21	27	30.0	1.2329e-03	1.3150e-03	1.4189e-03
PB.2.4	7	7	10.0	4.1097e-04	3.4091e-04	4.7297e-04
PB.3.1	3	3	3	1.7613e-04	1.4611e-04	1.4189e-04
PB.4.1	5	6	6	2.9355e-04	2.9221e-04	2.8378e-04
PB.5.1	2	2	2	1.1742e-04	9.7404e-05	9.4594e-05
PB.6.2	2	2	3.0	1.1742e-04	9.7404e-05	1.4189e-04
PB.6.3	4	5	6.0	2.3484e-04	2.4351e-04	2.8378e-04
PB.7.1	8	12	12	4.6968e-04	5.8443e-04	5.6756e-04
PB.8.1	2	3	3	1.1742e-04	1.4611e-04	1.4189e-04
PB.9.1	3	3	4.0	1.7613e-04	1.4611e-04	1.8919e-04

**Comment by Magdoll** [comment]
Hi @xogur ,

It appears a branch merge I did a while back kept coming back to haunt me. It's a bug that I have fixed and is now in v4.1. Let me know.

--Liz

**Comment by xogur** [comment]
Hi Magdoll,

Thank you very much Magdoll! The error has been fixed and it is working well!

Taehee

-sh-3.2$ chain_samples.py test.config norm_nfl
Sanity checking. Retrieving PBIDs from /isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/tofu2/evaluate_tofu2/collapse3/test.collapsed.group.txt,/isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/tofu2/evaluate_tofu2/collapse3/test.collapsed.gff,/isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/tofu2/evaluate_tofu2/collapse3/test.collapsed.abundance.txt...
Sanity checking. Retrieving PBIDs from /isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/smrtanalysis_3/bax2bam/collapse/collapse2/test.collapsed.group.txt,/isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/smrtanalysis_3/bax2bam/collapse/collapse2/test.collapsed.gff,/isi-dcnl/user_data/Seq/pacbio_analysis/thkang/IsoSeq_test/Alzheimer_isoseq/smrtanalysis_3/bax2bam/collapse/collapse2/test.collapsed.abundance.txt...
Chained output written to:
all_samples.chained.gff
all_samples.chained_ids.txt
all_samples.chained_count.txt
all_samples.chained.rep.fq
