### ISSUE TITLE
Forward link display 404

### ISSUE THREAD

**Issue by wzhang42** [Magdoll/cDNA_Cupcake#225]
I found there is one description as the following 
" ....
I work mostly with [**PacBio transcriptome (Iso-Seq data**)](https://github.com/PacificBiosciences/cDNA_primer/wiki), these are all used for cDNA data, hence cDNA_Cupcake. "
However, when I click the PacBio transcriptome. The forward link (https://github.com/PacificBiosciences/cDNA_primer/wiki) display as 404.   Could you share with me a valid link to access these playing with data. Much appreciated!

**Comment by Magdoll** [comment]
Hi @wzhang42  - yes there's a new wiki at
https://github.com/Magdoll/cDNA_Cupcake/wiki/Iso-Seq-Public-Datasets
