### ISSUE TITLE
cluster id mismatch issue in get_abundance_post_collapse.py

### ISSUE THREAD

**Issue by ssutharzan** [Magdoll/cDNA_Cupcake#229]
Hi,
It seems like get_abundance_post_collapse.py is unable to get the abundance possibly due to the cluster id mismatch between _test.collapsed.group.txt_ and _cluster_report.csv_ files. For example in provided test data the cluster _sample1_HQ_transcript/48_ in _test.collapsed.group.txt_ is represented as _transcript/48_ in _cluster_report.csv_ .  I had the same issue with my data. Matching the cluster ids only using the numerical part or _transcript/<numerical part>_ could solve this issue.

I think this issue has been noted before in #186 #61 #146 
Thanks!

**Comment by ssutharzan** [comment]
@Magdoll I was wondering whether are you working on this. Is it OK if I submit a pull request with a potential fix to this issue?
Thanks!

**Comment by Magdoll** [comment]
@ssutharzan  you can go ahead with a PR :)

**Comment by ssutharzan** [comment]
> @ssutharzan you can go ahead with a PR :)

@Magdoll I made the PR :) Thanks!
