### ISSUE TITLE
run_preCluster.py

### ISSUE THREAD

**Issue by jordur** [Magdoll/cDNA_Cupcake#237]
Hi!
I would like to analyze some PacBio data without a reference genome. To this end, I tried to follow the following tutorial:
https://github.com/Magdoll/cDNA_Cupcake/wiki/Tutorial:-Collapse-redundant-isoforms-without-genome
I used cd-hit  but then I was unable to find the run_preCluster.py script.
I saw [here](https://github.com/Magdoll/Cogent/issues/48#issue-359958461) that it was a piece of software from cDNA_cupcake. However, after being installed, I did not find the script neither in the git repository  nor in the build directory created after running python setup.py build.
I just found a reference about the run_preCluster.py on the README.md page:
 **2019.12.30 updated to v9.2.0. fixed support for running `run_preCluster.py` that is used by Cogent**

Since I would like to run the family finding over a large dataset (~ 91857 sequences), can anyone give me a clue about how to analyze such a large dataset?
Regards,

**Comment by Magdoll** [comment]
Hi @jordur  - preCluster.py is no longer supported. Most of the Cupcake code is on its way to getting deprecated.
If you have Iso-Seq data, I recommend going to [isoseq.how](https://isoseq.how/) for the latest software.

-Liz
