### ISSUE TITLE
setup.py requires sklearn instead of scikit-learn

### ISSUE THREAD

**Issue by cyrilcros** [Magdoll/cDNA_Cupcake#238]
https://github.com/Magdoll/cDNA_Cupcake/blob/81b7e7f6aeb53e15c11dd30a68a498a58e5f390a/setup.py#L40

The installation via `python setup.py build / python setup.py install` fails because sklearn has been deprecated (and raises error as of December 22). Switching to scikit-learn on that line succeeds.

**Comment by Magdoll** [comment]
Hi thank you for letting me know! That said Cupcake will be deprecated soon. FYI.
