### ISSUE TITLE
fusion_collate_info.py KeyError: 'count_fl'

### ISSUE THREAD

**Issue by sonyuna90** [Magdoll/cDNA_Cupcake#240]
Hi,

I found that this fusion_collate_info.py script gave me this error. I saw other people reported this before but it seems that I can't find any solutions. This is my code I run.

# my run
fusion_collate_info.py CR183p1-141124.lq_isoforms.fasta.fusion CR183p1-141124_classification.txt       gencode.v38.annotation.gtf       --genome /projects/abv/GRC/sonyx/LR_analysis/LIQA/ref/hg38.fa

Finished reading reference genome /projects/abv/GRC/sonyx/LR_analysis/LIQA/ref/hg38.fa.
Reading gencode.v38.annotation.gtf to extract gene name to ENSG ID mapping...
Traceback (most recent call last):
  File "/ui/abv/sonyx/miniconda/envs/anaCogent/bin/fusion_collate_info.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==29.0.0', 'fusion_collate_info.py')
  File "/ui/abv/sonyx/miniconda/envs/anaCogent/lib/python3.7/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/ui/abv/sonyx/miniconda/envs/anaCogent/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/ui/abv/sonyx/miniconda/envs/anaCogent/lib/python3.7/site-packages/cupcake-29.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_collate_info.py", line 236, in <module>
    include_Mt_genes=args.include_Mt_genes)
  File "/ui/abv/sonyx/miniconda/envs/anaCogent/lib/python3.7/site-packages/cupcake-29.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_collate_info.py", line 95, in collate_info
    count_d[r['pbid']] = int(r['count_fl'])
KeyError: 'count_fl'

**Comment by sonyuna90** [comment]
IF something has similar issues, I found that the FL count file has a header so I removed them and didn't have an issue with running this. 

![image](https://github.com/Magdoll/cDNA_Cupcake/assets/105462597/88d477a6-5fa6-4212-9da7-921ad699350f)

**Comment by tky199996** [comment]
> 你好，
> 
> 我发现这个 fusion_collat​​e_info.py 脚本给了我这个错误。我之前看到其他人报告过这个问题，但似乎找不到任何解决方案。这是我运行的代码。
> 
> # 我的跑步
> fusion_collat​​e_info.py CR183p1-141124.lq_isoforms.fasta.fusion CR183p1-141124_classification.txt gencode.v38.annotation.gtf --genome /projects/abv/GRC/sonyx/LR_analysis/LIQA/ref/hg38.fa
> 
> 读完参考基因组/projects/abv/GRC/sonyx/LR_analysis/LIQA/ref/hg38.fa。 读取 gencode.v38.annotation.gtf 以提取基因名称到 ENSG ID 映射... 回溯（最近一次调用最后）： 文件“/ui/abv/sonyx/miniconda/envs/anaCogent/bin/fusion_collat​​e_info.py”，行4、在 **import** ('pkg_resources').run_script('cupcake==29.0.0','fusion_collat​​e_info.py') 文件“/ui/abv/sonyx/miniconda/envs/anaCogent/lib/python3.7/site- packages/pkg_resources/ **init** .py”，第 672 行，在 run_script self.require(requires)[0].run_script(script_name, ns) 文件“/ui/abv/sonyx/miniconda/envs/anaCogent/lib/python3.7 /site-packages/pkg_resources/ **init** .py”，第 1472 行，在 run_script exec(代码、命名空间、命名空间) 文件“/ui/abv/sonyx/miniconda/envs/anaCogent/lib/python3.7/site-packages/ cupcake-29.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_collat​​e_info.py”，第 236 行，在 include_Mt_genes=args.include_Mt_genes 中） 文件“/ui/abv/sonyx/miniconda/envs/ anaCogent/lib/python3.7/site-packages/cupcake-29.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_collat​​e_info.py”，第 95 行，在 collat​​e_info count_d[r['pbid ']] = int(r['count_fl']) KeyError: 'count_fl'

Hello, I have recently encountered some difficulties when using SQANTI3 and cDNA_Cupcake. For some reasons, I need to use SQANTI3 and cDNA_Cupcake at the same time. I installed SQANTI3 and cDNA_Cupcake according to the installation requirements. In order to ensure that the two will not interfere with each other, I created I created two conda environments and ran them separately. I once ran both software successfully, but I didn’t know what environment variables were changed the next day, so that the following error occurred when running funsion_finder.py, but when I switched to a new environment and ran SQANTI3 can run successfully, can anyone help me, I want to know how can I run fusion_finder.py successfully，thank you
![微信图片_20240320152250](https://github.com/Magdoll/cDNA_Cupcake/assets/120616828/fb15dfa3-ffa5-4336-a0ab-281cb727351a)

**Comment by Magdoll** [comment]
Hi please use other fusion software such as:

https://github.com/PacificBiosciences/pbfusion
https://github.com/TrinityCTAT/CTAT-LR-fusion

Cupcake fusion is no longer supported. This repo is being deprecated.
