### ISSUE TITLE
installing error for Cupcake ToFU

### ISSUE THREAD

**Issue by Iceylee** [Magdoll/cDNA_Cupcake#25]
@Magdoll Hi, when I tried to install cupcake tofu 
 many warnings generated in `python setup.py build`step. 
![2017-12-20 9 22 16](https://user-images.githubusercontent.com/15882771/34186536-54026ffe-e567-11e7-8ed3-e7e9b172af84.png)
![2017-12-20 9 22 30](https://user-images.githubusercontent.com/15882771/34186646-fa99b64c-e567-11e7-8457-49ccdb4eae49.png)

More warnings saying "unused function" generated in `python setup.py install` step.
And end up like this:
![2017-12-20 9 19 36](https://user-images.githubusercontent.com/15882771/34186502-07579364-e567-11e7-958a-4587bbe991ab.png)

I am using Mac OS X, a new Anaconda environment with python 2.7. created like this:
`conda create -n cupcake Anaconda python=2`
`conda install biopython
source activate cupcake`

Please help...

**Comment by Magdoll** [comment]
Hi,
In general, we do not support Mac OS. All our code is tested on Linux (CentOS and Ubuntu) and the current Cupcake version (4.2) works on both linux distributions. 

--Liz
