### ISSUE TITLE
Wrong gene classification

### ISSUE THREAD

**Issue by Trandamere** [Magdoll/cDNA_Cupcake#28]
Hi:
    I find a problem about wrong gene classification.
    
![2](https://user-images.githubusercontent.com/24996924/35737244-d56c764a-0865-11e8-965a-fd80e84f6497.jpg)
    In the picture,PB.583 have two part,PB.583.1 PB.583.2 PB583.3 PB.583.4   and PB.583.5 PB.583.6 PB.583.7  PB.583.8. It is obviously two genes. 
    I think the reason that wrong gene classification is the PB.584 link the PB.583 two part.
    There are many such situations here.like this:
![default](https://user-images.githubusercontent.com/24996924/35737769-a2cefb2a-0867-11e8-929f-43e4a7979bde.jpg)

**Comment by Trandamere** [comment]
I suggest you separate the positive and negative chains to classify.

**Comment by Magdoll** [comment]
@Trandamere ,

This may be a bug. The different strands are processed independently so this should not happen. Would it be possible to share the mapped reads (fasta or fastq) and SAM file for just this region? If it's mapping to a known ref like hg19 or hg38, I will only need the read fasta/fastq. You can email it to etseng@pacb.com.

**Comment by Trandamere** [comment]
@Magdoll 
This is the fasta and SAM file of PB583
[PB583.zip](https://github.com/Magdoll/cDNA_Cupcake/files/1799421/PB583.zip)

**Comment by Magdoll** [comment]
Hi @Trandamere ,
Thanks for sharing the dataset! You are right...while the strands were processed separately, in the initial grouping stage they were grouped together. I've pushed the code fixes to Cupcake version 5.2 (if you use tags, it is tagged [tofu2_v19](https://github.com/Magdoll/cDNA_Cupcake/tree/tofu2_v19))

You should now see three gene groups (PB.1 and PB.2 for the two + strand genes, PB.3 for the - strand). 

Please let me know if this fixes your problems.

--Liz

**Comment by Trandamere** [comment]
@Magdoll 
   Hi,The proble is is solved after using Cupcake version 5.2!
