### ISSUE TITLE
A problem about using Cogent to collapse redundant transcripts in absence of genome

### ISSUE THREAD

**Issue by ClearloveMiao** [Magdoll/cDNA_Cupcake#32]
Hi!
Before I want to use Cogent and Cupcake to collapse redundant transcripts in absence of genome, what kinds of data I should use? 
After SMRTLink, I have had the `polished consensus fasta`, `polished hq fasta`, `polished lq fasta`, and which fasta file should be used to do this collapsing jobs?
Thanks for any suggestion!

**Comment by Magdoll** [comment]
Hi @ClearloveMiao ,
Please use `polished hq fasta` only.

You will need that both as input to Cogent and later, when you have the output of Cogent, map to the output of Cogent and run collapse.
--Liz

**Comment by ClearloveMiao** [comment]
Hi, @Magdoll ,
Thanks for your reply!

Another problem, before I am going to do collapsing job using `polished hq fasta`, should I use `LorDEC` to correct and `CD-HIT-est` to remove redundant with `polished hq fasta`? 
Or, another way for asking, should the input fasta file of Cogent be processed by `LorDEC` and `CD-HIT-est` first?

Thanks for any suggestion!

**Comment by Magdoll** [comment]
You don't need to run CD-HIT as it is redundant (and not as effective) as the actual collapse scripts (`collapse_isoforms_by_sam.py`)

You can run LorDEC against the HQ before you run Cogent and/or collapse.

--Liz
