### ISSUE TITLE
Trouble w/ install/run of Cupcake

### ISSUE THREAD

**Issue by aksenia** [Magdoll/cDNA_Cupcake#36]
Hi Liz,

I installed Cupcake via anaCogent env and can't get it work. To my knowledge the error I observe (see screen) mean I try running it with different python that was used to build it, but how is this possible, I use anaCogent python (white is my user and server name masked).
![cupcake_install](https://user-images.githubusercontent.com/6505876/42640269-3a9f85e8-85f2-11e8-83ad-3106ac825156.png)

**Comment by Magdoll** [comment]
Hi @aksenia ,

You may have conflicting Python versions under the anaconda2 environment esp if you have already had anaconda2 installed before.

My two cents is to install a new anaconda repo that is not `~/anaconda2`, maybe like `~/anaconda3`.

Let me know how it goes..

--Liz

**Comment by aksenia** [comment]
Thank you so much, I understand this kind of problem is hard for you to comment on because it is rather a problem of system config. I solved it myself - I had some messed up PATH for some reason, perhaps from several various environments activation. Wiping the session clean and reinstalling everything from scratch helped.
