### ISSUE TITLE
Classification of adjacent genes in In the same direction by collapse_isoforms_by_sam.py

### ISSUE THREAD

**Issue by Trandamere** [Magdoll/cDNA_Cupcake#49]
Hi:
I have a problem with the classification of genes.
![pt](https://user-images.githubusercontent.com/24996924/49921148-9c6ba180-fee7-11e8-9972-98d8a726d948.png)
The PB.6693 is classified as the same gene without problems,because thera have PB.6693.3 long isoform.
![rong](https://user-images.githubusercontent.com/24996924/49921255-f1a7b300-fee7-11e8-9c85-e3e6ea583a6a.png)
But like this, it is wrong to classify the same gene because the borders are partially overlapped.
Is there a way to solve it?

**Comment by Magdoll** [comment]
Hi @Trandamere ,

As you have observed, this point, collapse script is very generous with grouping genes --- any transcripts that overlap by 1 bp on the same strand are grouped together as a "locus". 

I don't have plans to introduce more nuanced gene-clustering at this point, unfortunately. 

If you have a reference genome with existing annotation, you can compare the results against [SQANTI](https://github.com/Magdoll/SQANTI2/) to help further tease the genes apart. 

Ultimately, the goal of the collapse script is to identify transcribed loci, not to identify genes per se. That requires expertise and manual curation.

--Liz

**Comment by Trandamere** [comment]
Thank you！
