### ISSUE TITLE
Issue with install of latest commit

### ISSUE THREAD

**Issue by bajtaur** [Magdoll/cDNA_Cupcake#5]
I have been trying to install the most recent commit, but have been running into errors. Running setup.py gives me 

running install
running bdist_egg
running egg_info
creating cupcake.egg-info
writing cupcake.egg-info/PKG-INFO
writing dependency_links to cupcake.egg-info/dependency_links.txt
writing requirements to cupcake.egg-info/requires.txt
writing top-level names to cupcake.egg-info/top_level.txt
writing manifest file 'cupcake.egg-info/SOURCES.txt'
error: package directory 'cupcake2' does not exist

Tracing this issue shows the addition of requirements for "'cupcake2', 'cupcake2.io', 'cupcake2.ice2'" in the newest commit, but I can't find evidence of this package in the rest of the repository. I'm assuming there are files missing?

Everything installs fine prior to your commit a few days back.

**Comment by Magdoll** [comment]
my bad. cupcake2/ has now been added. it should work now.

**Comment by bajtaur** [comment]
Great, issue solved. Thank you.
