### ISSUE TITLE
filter_by_count failed

### ISSUE THREAD

**Issue by yuqiu77** [Magdoll/cDNA_Cupcake#52]
Data was generated by isoseq3 in SMRTLINK 6.0.  header is like:
@multiple_samples_HQ_transcript/0

filter by count.py generated error:

Traceback (most recent call last):
  File "/usr/local/bin/filter_by_count.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==6.1', 'filter_by_count.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cupcake-6.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/filter_by_count.py", line 106, in <module>
    filter_by_count(args.input_prefix, output_prefix, args.min_count, args.dun_use_group_count)
  File "/usr/local/lib/python2.7/dist-packages/cupcake-6.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/filter_by_count.py", line 40, in filter_by_count
    fl_count, p_count = tmp.split('p')
ValueError: need more than 1 value to unpack

**Comment by Magdoll** [comment]
Hi @yuqiu77 ,

Please add the `--dun_use_group_count` option and this error should go away.

THanks,
--Liz

**Comment by juheon** [comment]
Could I use 'filter_by_count.py' for post-collapsing reads of FLNC reads (ISO-seq3)?

According to the Wiki, I need to an output of 'get_abundance_post_collapse.py' to run 'filter_by_count.py'. However, since I use FLNC reads instead of clustered reads, I can't run 'get_abundance_post_collapse.py' due to the absence of 'cluster_report.csv', which is the output of the clustering step.

I want to filter out singleton FLNC reads as ISO-seq3 clustering does

**Comment by Magdoll** [comment]
Hi @juheon ,

You can make a "mock" abundance.txt file for the FLNC collapsed result using the Linux commands below. 

Suppose your collapsed output prefix is out.collapsed.xxxx. You need to generate the file `output.collapsed.abundance.txt`.

```
echo -e "pbid\tcount_fl" > output.collapsed.abundance.txt
paste <(awk '{print $1}' output.collapsed.group.txt) <(awk -F , '{print NF}' output.collapsed.group.txt ) >> output.collapsed.abundance.txt
```

This will generate an output that has the format:

```
pbid    count_fl
PB.1.1  1
PB.1.2  2
PB.1.3  2
PB.2.1  26
PB.2.2  1
PB.2.3  37
PB.2.4  2
```

which then allows you to run:

```
filter_by_count.py output.collapsed
```
