### ISSUE TITLE
Tools didn't support slightly changed transcript id

### ISSUE THREAD

**Issue by XiaoyuZhan520** [Magdoll/cDNA_Cupcake#56]
Hello, I have 3 samples in a group and I have 3 groups. I generated isoseq data for each sample and ran Isoseq3. In the following analysis, I merged 3 samples in a group. To tell each transcript generated from each sample. I change transcript ID, for example , from transcript/0 to [group1_sample1]transcript/0.

However, a lot of tools broke down while using the changed transcript ID, such as cupcake,tofu,get_abundance_post_collapse.py and sqanti.

Here is error information:
Exception: cluster_id [group1_sample1]transcript/0 is not a valid cluster ID!

Please feel free if you need any more information! Many thanks in advanced!

**Comment by Magdoll** [comment]
Hi @XiaoyuZhan520 ,
Can you please modify the transcript IDs from

```
transcript/0
transcript/1
```

to

```
sample1_HQ_transcript/0
sample1_HQ_transcript/1
```

And make sure you have the latest Cupcake repo and try running again?
I tested it just now and it works for me.

--Liz

**Comment by Magdoll** [comment]
Closing unless user reopens.
