### ISSUE TITLE
Filter away 5' degraded isoforms didn't accept fasta input

### ISSUE THREAD

**Issue by XiaoyuZhan520** [Magdoll/cDNA_Cupcake#57]
Hello Liz,

I corrected transcripts with RNA-Seq data, and the did the mapping by GMAP, collapsed by TOFU. 
When I used Cupcake ToFU to filter away 5' degraded isoforms, it end with *.all.collapsed.rep.fq does not exist. Abort!

I used fasta file as input, it worked while collapsing and obtaining associated count information. 
How can I run the filter step with fasta file?

Thanks!

**Comment by XiaoyuZhan520** [comment]
When doing rarefaction analysis, it also asked for fastq file

'It will automatically look for test.gff, test.abundance.txt and test.rep.fq, so make sure the three files exist.'

https://github.com/Magdoll/cDNA_Cupcake/wiki/Annotation-and-Rarefaction-Wiki

**Comment by Magdoll** [comment]
Hi @XiaoyuZhan520 ,

Please first convert fasta input to fastq using scripts such as `fa2fq.py` from [Cupcake/sequence](https://github.com/Magdoll/cDNA_Cupcake/wiki/Sequence-Manipulation-Wiki#convert).
