### ISSUE TITLE
Install Issue and Chain Samples Question

### ISSUE THREAD

**Issue by j-baller** [Magdoll/cDNA_Cupcake#6]
Addition of cupcake2.tofu2 dependency to setup.py without associated files. 

How am I meant to execute the chain_samples.py script? I suspect it needs to be installed and it doesn't appear in the setup.py. If I call it directly it is having trouble resolving the module:

Traceback (most recent call last):
  File "cDNA_Cupcake/cupcake/tofu/counting/chain_samples.py", line 9, in <module>
    from cupcake.tofu.counting import combine_abundance_across_samples as sp
ImportError: No module named counting

**Comment by Magdoll** [comment]
I've cleaned up the `setup.py` which previously got incorrectly overwritten by an older version of setup.py. 

`chain_samples.py` should be in the executable bin and work now. Let me know.
