### ISSUE TITLE
issues getting abundance and counts

### ISSUE THREAD

**Issue by ysf39039** [Magdoll/cDNA_Cupcake#61]
Hi, 

I am a newbie with iso-seq data. I have gone through and mapped the transcripts using GMAP, sorted, then collapsed redundant isoforms. I am not trying to get counts. I received the cluster_report.csv from our collaborators. 

I first tried get_abundance_post_collapse.py test.collapsed TD_00552_4995_clusterrpt.csv

I got 

_csv.Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?

So i did: dos2unix TD_00552_4995_clusterrpt.csv.

I received the same error 

So then I tired 

tr -d '\r' <TD_00552_4995_clusterrpt.csv> tmp.csv
get_abundance_post_collapse.py test.collapsed tmp.csv

This worked, however, the files I get in return do not have counts. Any sugestions as to where I might be making a mistake? 

Thank you in advance.

**Comment by Magdoll** [comment]
Hi @ysf39039 

This definitely looks like some potential newline/UNIX character issue.

Are you willing to share the collapsed files + cluster CSV over email confidentially?

If so, plz provide an email address.

--Liz

**Comment by ysf39039** [comment]
Yes, of course. Email is yesai.fstkchyan@icahn.mssm.edu 
I have a hyperlink to the folder with everything I have done so far. 

Thank you for the help, Liz! 

--Yesai

**Comment by Magdoll** [comment]
Hi @ysf39039 request has been sent

**Comment by Magdoll** [comment]
Closed after OP fixed the problem on their end.
