### ISSUE TITLE
Line discrepancies and large transcripts 

### ISSUE THREAD

**Issue by ysf39039** [Magdoll/cDNA_Cupcake#63]
Hi, 

I am working on iso seq data and using cupcake for the collapsing. I can get all the scripts to run fine with the correct outputs (collapse, get abundance, filter etc...), however, there are line discrepancies between my .gff, .rep.fq, and .group.txt. Am i correct in thinking the number of lines between these files should be exactly the same? Moreover, I get huge transcripts that span multiple genes after the collapsing. Any thoughts on where the mistake may be? I have max intro length set to 200000 using GMAP. 

Thank you in advance.

**Comment by Magdoll** [comment]
Hi @ysf39039 ,
The line numbers are supposed to be different.

In .gff, each transcript is represented by multiple lines, each line being an exon.

In .ref.fq, each transcript is represented by 4 lines (sequence ID, sequence, quality ID, quality).

In .group.txt, each transcript is represented by one line.

So it is expected they are different.

-Liz
