### ISSUE TITLE
Question: which annotation files should be used during step "Summarizing and Scrubbing Splice Junctions Across Samples"?

### ISSUE THREAD

**Issue by bioinformatist** [Magdoll/cDNA_Cupcake#65]
@Magdoll Hi my friend,
I have already pre-processed my sequences with iso-seq3 and before I can chain samples together, I need to scrub all AS events from my samples according to [this tutorial](https://github.com/Magdoll/cDNA_Cupcake/wiki/Summarizing-and-Scrubbing-Splice-Junctions-Across-Samples).

Firstly, I need to prepare a `summarize.config` as below:

```pre
SAMPLE=sample1;sample1/
SAMPLE=sample2;sample2/
SAMPLE=sample3;sample3/

GFF_FILENAME=original.gff
GENOME_FILENAME=hg38.fa
JUNCTION_FILENAME=gencode.v25.junctions.bed
```

That is what I'm confused. For instance, I would already have a series of `.gff` like `m54297_190108_172632.collapsed.min_fl_2.filtered.gff` and `m54297_190108_070530.collapsed.min_fl_2.filtered.gff` after collapsing and filtering all samples as [instructions here](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake-ToFU%3A-supporting-scripts-for-Iso-Seq-after-clustering-step).

So which one (or is there a method for summarizing them into single file?) should be fill to `GFF_FILENAME` field?

Thanks in advance 😺

**Comment by bioinformatist** [comment]
I process them separately now. That means, I build serveal contig files (each one for a sample) and use their own gff file accordingly. Is it right?

**Comment by Magdoll** [comment]
Hi @bioinformatist ,

For each sample, it expects a GFF in that folder.

So by your sample, it would expect the following files:

```
sample1/original.gff
sample2/original.gff
sample3/original.gff
```
