### ISSUE TITLE
no cluster_report.csv output

### ISSUE THREAD

**Issue by mulchchristina** [Magdoll/cDNA_Cupcake#66]
no cluster_report.csv output from collapse script...
when running:
collapse_isoforms_by_sam.py --input hq_transcrpts.fastq --fq -s hq_isoforms.fastq.sorted.sam --dun-merge-5-shorter -o test
I get these output files but no CSV...... 
 test.ignored_ids.txt
test.collapsed.gff.unfuzzy
test.collapsed.group.txt.unfuzzy
test.collapsed.gff
test.collapsed.group.txt
 test.collapsed.rep.fq

Any ideas about why this may occur?

**Comment by Magdoll** [comment]
Hi @mulchchristina ,
`collapse_isoforms_by_sam.py` does not generate `cluster_report.csv`. The `cluster_report.csv` is usually generate by the `isoseq3 cluster` program.

-Liz
