### ISSUE TITLE
Question on fusion_finder.py

### ISSUE THREAD

**Issue by ljw90607** [Magdoll/cDNA_Cupcake#67]
Dear @Magdoll,

I am currently trying to run fusion_finder.py using nanopore data for a test.
Code used for the run is shown below:
`fusion_finder.py --input input_dedup.fastq --fq -s input_dedup_minimap2.sam -o input_dedup_minimap2.sam_fusion`

I have received the error as below which I could not figure out what it meant,

> raise Exception, "Unable to find qID {0} in the input fasta/fastq!".format(self.qID)
> Exception: Unable to find qID 1 PM-AU-0002-N-A1_0 in the input fasta/fastq!

If you could let me know how I get through this, I would really appreciate it!

Thank you 

Jungwoo Lee

**Comment by Magdoll** [comment]
Hi @ljw90607 ,

Looks like an ID mismatch error. Please make sure the qID also exists in the SAM file. Maybe minimap2 trimmed the sequence IDs? In that case, you may need to manually modify the sequence IDs in the original FASTQ file.

--Liz
