### ISSUE TITLE
Single Cell IsoSeq

### ISSUE THREAD

**Issue by ashokpatowary** [Magdoll/cDNA_Cupcake#68]
@Magdoll Is there any way to use the fasta or fastq file for "Detect UMIs and Cell Barcodes" step. In dropseq PCR FP and RP is reverse complement of each other. So lima cannot be used. I have to convert the ccs into fastq and then trim the primer. Now, I cannot proceed as the bam file I generated appear not to be a valid PacBio BAM file for the tool. Is there any solution to it?

**Comment by Magdoll** [comment]
Hi @ashokpatowary ,

Are you sure the DropSeq data is completed symmetric? I work on DropSeq too and there's an overhang.

This is what my DropSeq primers look like:

```
>5p
AAGCAGTGGTATCAACGCAGAGTGAATGGGG
>3p
GTACTCTGCGTTGATACCACTGCTT
```


--Liz

**Comment by ashokpatowary** [comment]
@Magdoll yes. That is what I was expecting (CCC overhang). Unfortunately, after sequencing the library (library was generated by a collaborator and was already used in Illumina Sequencing) I did not find any CCC overhang I was looking for. So, I try to extract the ~35 bp from the from both the ends to give a manual look. I did not help much. So, I changes the orientation of all the sequences with polyA at the 3' ends and after polyA there should be only 45bp. So, practically, I should have the CCC/GGG overhang  for majority of the sequence at the 5' ends. Thereafter I looked for the starting position of "ATGGGGG" at the 5' ends.  For ~30% sequence I found the "ATGGGG" start position at 27/28/29 bp position from the start. For remaining I can see the "AAGCAGTGGTATCAACGCAGAGTGA" sequence with 1/2 bp mismatches but no "ATGGGGG". And also I can detect the barcode used. However, I should let you know the initial library used for PCR amplification is a very old one but I dont think it should caus such issues. Also, If you see the SMART PCR primer they are actually complementary to each other. In such condition what should be the best way forward: should I proceed with only 30% of the reads or is the there any way I can use your recommended pipeline.

**Comment by Magdoll** [comment]
Hi @ashokpatowary ,

Lack of 5' overhang means you have a lot of RT artifacts.  In other words, likely bad library prep. The purpose of `lima` is to correctly identify and point out library issues.

I would recommend trying to first run the pipeline the right way --- suffering the low yield --- and go through the whole pipeline first to see how the data looks when it contains the correct 5' and 3' primers. There is no guarantee the RT artifacts (those lacking 5' overhang) are full-length. 

--Liz
