### ISSUE TITLE
IsoPhase

### ISSUE THREAD

**Issue by ctxchris** [Magdoll/cDNA_Cupcake#69]
I'm trying to phase my IsoSeq transcripts and follow the IsoSeq 3.1 pipeline for pre-processing:
`ccs`
`lima`
`isoseq3 refine`
`isoseq3 cluster`
`isoseq3 polish`

I interpreted the note 

> By default, Iso-Seq 3 is run with CCS QV=OFF! Hence, all QVs will be 0. In order to run IsoPhase, you must run CCS with QV=ON!

to run `ccs -polish` to get real quality values.
Is that correct?

According to 
> bamtools convert -format fastq -in unpolished.flnc.bam > flnc.fastq

I should get FASTQ files with real qual values from the unpolished FLNC reads that are generated during the isoseq3 cluster.  The problem is that *ccs.bam and *flnc.bam contain qual values, the output of isoseq3 cluster, *unpolished.bam doesn't. Or should I take the unclustered FLNC reads for phasing? 

Thanks,
Chris

**Comment by Magdoll** [comment]
Hi @ctxchris ,

Yes you run `ccs --polish` to get the QV values.

You only need FLNC to have the QV values - correct that `unpolished.bam` doesn't contain QVs but they're not used for IsoPhase input.

--Liz

**Comment by ctxchris** [comment]
Understood.

run_phase.py exits with 

> Cannot import vcf! Please install bio-vcf!

I installed cDNA_Cupake as outlined (https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake-ToFU%3A-supporting-scripts-for-Iso-Seq-after-clustering-step#install) and also have biopython installed in the same conda environment.

Which package is this referring to?

Thanks,
Chris

**Comment by Magdoll** [comment]
Hi @ctxchris ,
My bad! please install [bio-vcf](https://anaconda.org/bioconda/bio-vcf)

```
conda install -c bioconda bio-vcf 
```
