### ISSUE TITLE
Cannot find HQ FASTQ in job directory! Does not look like Iso-Seq1, 2, or 3 jobs!

### ISSUE THREAD

**Issue by tomasflyo** [Magdoll/cDNA_Cupcake#71]
Hi,

I successfully ran an IsoSeq3 analysis, after which I am tried using the `demux_isoseq_with_genome.py` command, as explained in the [tutorial.](https://github.com/Magdoll/cDNA_Cupcake/wiki/Tutorial:-Demultiplexing-SMRT-Link-Iso-Seq-Jobs)
This resulted in the following error:

> Cannot find HQ FASTQ in job directory! Does not look like Iso-Seq1, 2, or 3 jobs!

So I tried running the command with the specific file names, and not the hard link of the job path:

`python demux_isoseq_with_genome.py --mapped_fastq mapped.fastq --read_stat mapped.read_stat.txt --classify_csv classify_report.csv -o job304.mapped_fl_count.txt
`

The relevant part of the [tutorial ](https://github.com/Magdoll/cDNA_Cupcake/wiki/Tutorial:-Demultiplexing-SMRT-Link-Iso-Seq-Jobs#providing-files-directly-instead-of-job-dir-1) only notes which specific files should be used in case of isoseq1 run, but not for isoseq3. So I used these:

![Untitled](https://user-images.githubusercontent.com/46571634/57979554-19b3b900-7a28-11e9-8cb2-2b44bcf10871.jpg)

and I received the following error message:

>   File "demux_isoseq_with_genome.py", line 134
>    raise Exception, "{0} listed more than once in {1}!".format(\
>                   ^
>SyntaxError: invalid syntax

I would appreciate your help,
Thanks,
Tom

**Comment by Magdoll** [comment]
Hi @tomasflyo ,

You correctly identified all the files except `classify_report.csv`. The file you attempted to give it is in fact `cluster_report.csv`, hence the error.

`classify_report.csv` is not exposed in the SMRTLink UI. Identify the file path where the job is located and it should be similar to the following path:

```
<path_to_job>/tasks/isoseq3.tasks.refine-0/flnc.report.csv
```

The file should look like this:

```
id,strand,fivelen,threelen,polyAlen,insertlen,primer
m54119_190131_171128/67895969/ccs,+,28,25,30,8076,Clontech_5p--Clontech_3p
m54119_190202_095143/67371668/ccs,+,27,21,26,3860,Clontech_5p--Clontech_3p
m54026_190120_000756/25493646/ccs,+,32,24,24,3601,Clontech_5p--Clontech_3p
m54119_190202_095143/13697247/ccs,+,27,27,28,3432,Clontech_5p--Clontech_3p
m54119_190203_061153/71500416/ccs,-,23,31,27,3331,Clontech_5p--Clontech_3p
m54119_190203_061153/19071129/ccs,+,32,25,35,2843,Clontech_5p--Clontech_3p
m54119_190203_061153/49283521/ccs,-,26,33,62,2236,Clontech_5p--Clontech_3p
m54119_190202_095143/72613959/ccs,+,29,27,25,2317,Clontech_5p--Clontech_3p
m54119_190202_095143/34210219/ccs,+,46,25,30,2633,Clontech_5p--Clontech_3p
m54119_190202_095143/43319374/ccs,-,24,32,22,4049,Clontech_5p--Clontech_3p
```

**Comment by tomasflyo** [comment]
Hi,

Thanks for the reply.

No similar path/file exists in my job directory and subfolders.
I also searched for files that contain some of the keywords you mentioned
(i.e., fivelen, polyAlen, insertlen), but came up with nothing.

I'll contact tech support, but if you have any ideas in the meantime I
would be happy to know.

Best,
Tom
