### ISSUE TITLE
ERROR: scrub_sample_GFF_junctions.py

### ISSUE THREAD

**Issue by xogur** [Magdoll/cDNA_Cupcake#75]
Hello,

I am trying to chain fusion genes of two data sets.

After running 'fusion_finder.py', I did run the 'summarize_sample_GFF_junctions.py' and the 'scrub_sample_GFF_junctions.py'. The result of the 'summarize_sample_GFF_junctions.py' was ok. But, I got an error such as "KeyError: 'PBfusion.14.1'" after running the 'scrub_sample_GFF_junctions.py' as below. 

--------------------------------------------------------------------------
Scrubbed junction written to:  scrubbed.scrubbed.junction.bed
Traceback (most recent call last):
  File "/opt/Python/2.7.14/bin/scrub_sample_GFF_junctions.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==7.5', 'scrub_sample_GFF_junctions.py')
  File "/opt/Python/2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/Python/2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/opt/Python/2.7.14/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_64.egg/EGG-INFO/scripts/scrub_sample_GFF_junctions.py", line 286, in <module>
    scrub_sample_GFFs(sample_dirs, gff_filename, count_filename, group_filename, fastq_filename, args.output_prefix, tree)
  File "/opt/Python/2.7.14/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_64.egg/EGG-INFO/scripts/scrub_sample_GFF_junctions.py", line 157, in scrub_sample_GFFs
    os.path.join(d, output_prefix))
  File "/opt/Python/2.7.14/lib/python2.7/site-packages/cupcake-7.5-py2.7-linux-x86_64.egg/EGG-INFO/scripts/scrub_sample_GFF_junctions.py", line 227, in cleanup_scrubbed_files_redundancy
    r = count_d[bunch[0]]
KeyError: 'PBfusion.14.1'
--------------------------------------------------------------------------

It seemed that every output file were generated. But, in the output files, the scrubbed.abundance.txt was empty. The contents in the config file were as below.

----------------------------------------------------------------------------
SAMPLE=sample;../sample/fusion

GFF_FILENAME=hq_isoforms.fasta.fusion.gff
COUNT_FILENAME=hq_isoforms.fasta.fusion.abundance.txt
GROUP_FILENAME=hq_isoforms.fasta.fusion.group.txt
FASTQ_FILENAME=hq_isoforms.fasta.fusion.rep.fq
-----------------------------------------------------------------------------

Could you please give me some comments how to solve the issue? 

Thank you!

Taehee

**Comment by Magdoll** [comment]
Hi @xogur ,

scrub junctions is not really made to work with fusion...there's a complication with how fusions have to represented (becuz each "gene" PB.X has 2+ components like PB.X.1 and PB.X.2). I cannot immediately work on making scrub work for fusion right now but will keep this in mind.

--liz

**Comment by xogur** [comment]
Hello --liz,

Thank you for the answer!

I did try to do the scrub juctions becasue I wanted to chain two fusion
datasets. If so, the chain_samples.py doesn't work for the fusion datasets
as well?

Thank you,

xogur

2019년 6월 12일 (수) 오전 10:42, Elizabeth Tseng <notifications@github.com>님이 작성:

**Comment by Magdoll** [comment]
Hi @xogur ,

`chain_samples.py` does not work correctly with fusion.

You can use [chain_fusion_samples.py](https://github.com/Magdoll/cDNA_Cupcake/blob/master/cupcake/tofu/counting/chain_fusion_samples.py) instead.

**Comment by xogur** [comment]
Thank you so much! It is working.

2019년 6월 12일 (수) 오후 4:46, Elizabeth Tseng <notifications@github.com>님이 작성:
