### ISSUE TITLE
Annotation issue

### ISSUE THREAD

**Issue by xogur** [Magdoll/cDNA_Cupcake#78]
Hello,

I have another question. I have run the matchAnnot.py with the .sorted.sam produced by minimap2. But, I have gotten an error such as "IndexError: tuple index out of range". Please take a look at my log as below. 

I did also try to use the '--format alt' option of matchAnnot becasue it was working previously when I was with another Iso-Seq data (at that time, I did use the gmap alignment using the RSII data). But, the error has been same. 

I am not sure if I could leave this question here because you seem to be not the person who develop the tool. But, if you have had a similar experience, could you please give any suggestions including the other annotation tools? Thank you!

Best,

Taehee

-----------------------------------------------------------

minimap2 -ax splice -t 30 -uf --secondary=no -C5 ../GRCh38.p12.genome.fa ../polished.hq.fastq > ../polished.hq.fastq.sam

sort -k 3,3 -k 4,4n ../polished.hq.fastq.sam > ../polished.hq.fastq.sorted.sam

$ ../matchAnnot.py --gtf ../gencode.v30.annotation.gtf ../polished.hq.fastq.sorted.sam > ../polished.hq.fastq.sorted.sam.matchAnnot.txt
[DEBUG] 2019-06-11 17:52:28,886 [Annotations 13] version 20150611.01 loaded
[DEBUG] 2019-06-11 17:52:28,886 [Cluster 13] version 20150814.01 loaded
[DEBUG] 2019-06-11 17:52:28,886 [ClusterReport 11] version 20141029.01 loaded
[DEBUG] 2019-06-11 17:52:28,887 [CigarString 15] version 20150707.01 loaded
[DEBUG] 2019-06-11 17:52:28,888 [PolyA 17] version 20150402.01 loaded
[DEBUG] 2019-06-11 17:52:28,888 [matchAnnot 37] version 20150611.02 starting
[DEBUG] 2019-06-11 17:52:28,888 [Annotations 134] reading annotations in standard format from ../gencode.v30.annotation.gtf
[DEBUG] 2019-06-11 17:54:37,105 [Annotations 213] read 58870 genes, 208621 transcripts, 1279686 exons
[DEBUG] 2019-06-11 17:54:37,106 [matchAnnot 60] reading SAM file ../polished.hq.fastq.sorted.sam
Traceback (most recent call last):
  File "../matchAnnot.py", line 540, in <module>
    main()
  File "../matchAnnot.py", line 124, in main
    exons = cigar.exons()
  File "../CigarString.py", line 189, in exons
    self.variants.append ( ['D', count, exonList[-1].end+1, offset+exonList[-1].size, cf[2]] )     # +1: end is inclusive

**Comment by Magdoll** [comment]
Hi @xogur ,

Unfortunately MatchAnnot is no longer maintained by the author and I do not intend to support it. 

I actually highly recommend switching over to [SQANTI2](https://github.com/Magdoll/SQANTI2/) which I am actively supporting.

--Liz

**Comment by xogur** [comment]
Thank you! I will try it.

2019년 6월 13일 (목) 오전 9:35, Elizabeth Tseng <notifications@github.com>님이 작성:
