### ISSUE TITLE
python demux_by_barcode_groups.py

### ISSUE THREAD

**Issue by tomasflyo** [Magdoll/cDNA_Cupcake#79]
Hi,

I am running the python demux_by_barcode_groups.py in the following way:
`python demux_by_barcode_groups.py --pooled_fastx mapped.fastq mapped.fastq.sam job20190613.mapped_fl_count.txt output_demux  "('151149_5p','151149'),('150809_3p','150809')"`
and I get the following error message:

> Traceback (most recent call last):
>   File "demux_by_barcode_groups.py", line 8, in <module>
>     from cupcake.io.BioReaders import GMAPSAMReader
> ImportError: No module named cupcake.io.BioReaders

the fasta file I used in my analysis looks like this:
```
>151149_5p
AAGCAGTGGTATCAACGCAGAGTACATGGG
>151149_3p
CGCACTCTGATATGTGGTACTCTGCGTTGATACCACTGCTT
>150809_3p
CTCACAGTCTGTGTGTGTACTCTGCGTTGATACCACTGCTT
```

Could you help me with this error message? 

Thanks,
Tom

**Comment by Magdoll** [comment]
Hi @tomasflyo ,
The import error comes from not having compiled/installed Cupcake.

Please follow [instructions here](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake-ToFU%3A-supporting-scripts-for-Iso-Seq-after-clustering-step#install).

Let me know how it goes.

Thanks,
--Liz

**Comment by tomasflyo** [comment]
Hi Liz,

Thanks, installed.
Now I am getting:

> $ python demux_by_barcode_groups.py --pooled_fastx mapped.fastq mapped.fastq.sam job20190613.mapped_fl_count.txt output_demux "('151149_5p--150809_3p','150809'),('151149_5p--151149_3p','151149')"
>   File "demux_by_barcode_groups.py", line 21
>     raise Exception, "Unrecognized file suffix .{0}! Must end with .fasta or .fastq!".format(in_filename[in_filename.find('.'):])
>                                                                                                                                 ^
> TabError: inconsistent use of tabs and spaces in indentation
