### ISSUE TITLE
 duplicate  isoforms in chain_samples.py output？

### ISSUE THREAD

**Issue by 52teth** [Magdoll/cDNA_Cupcake#8]
Hi，
I have used command  'chain_samples.py  chain.cfg norm_nfl' to chain my isoseq collapsed result from two samples, But when I  check the "all_samples.chained.gff" file, I find that there's duplicate transcripts(PB.1.1 and PB.1.2):
chr1    PacBio  transcript      70      4943    .       +       .       gene_id "PB.1"; transcript_id "PB.1.1";
chr1     PacBio  exon    70      4943    .       +       .       gene_id "PB.1"; transcript_id "PB.1.1";
chr1     PacBio  transcript      70      4943    .       +       .       gene_id "PB.1"; transcript_id "PB.1.2";
chr1     PacBio  exon    70      4943    .       +       .       gene_id "PB.1"; transcript_id "PB.1.2";
chr1     PacBio  transcript      1143    3686    .       +       .       gene_id "PB.1"; transcript_id "PB.1.3";
chr1     PacBio  exon    1143    2231    .       +       .       gene_id "PB.1"; transcript_id "PB.1.3";
chr1     PacBio  exon    2292    3686    .       +       .       gene_id "PB.1"; transcript_id "PB.1.3";
chr1    PacBio  transcript      1215    6942    .       +       .       gene_id "PB.1"; transcript_id "PB.1.4";
chr1    PacBio  exon    1215    2219    .       +       .       gene_id "PB.1"; transcript_id "PB.1.4";
chr1     PacBio  exon    5669    6942    .       +       .       gene_id "PB.1"; transcript_id "PB.1.4";
Here is the chained ids in 'all_samples.chained_ids.txt': 
superPBID       sample-1    sample-2
PB.1.1  PB.1.1  PB.1.1
PB.1.2  PB.1.1  PB.2.1
PB.1.3  NA      PB.2.2
PB.1.4  NA      PB.2.3

Here is the collapsed.gff file for sample-1: 
chr1     PacBio  transcript      70      4943    .       +       .       gene_id "PB.1"; transcript_id "PB.1.1";
chr1     PacBio  exon    70      4943    .       +       .       gene_id "PB.1"; transcript_id "PB.1.1";
chr1     PacBio  transcript      1348    3693    .       -       .       gene_id "PB.2"; transcript_id "PB.2.1";
chr1     PacBio  exon    1348    3693    .       -       .       gene_id "PB.2"; transcript_id "PB.2.1";
And head lines in the collapsed.gff file for sample-2:
chr1     PacBio  transcript      70      1020    .       +       .       gene_id "PB.1"; transcript_id "PB.1.1";
chr1     PacBio  exon    70      1020    .       +       .       gene_id "PB.1"; transcript_id "PB.1.1";
chr1     PacBio  transcript      1033    4943    .       +       .       gene_id "PB.2"; transcript_id "PB.2.1";
chr1    PacBio  exon    1033    4943    .       +       .       gene_id "PB.2"; transcript_id "PB.2.1";
chr1     PacBio  transcript      1143    3686    .       +       .       gene_id "PB.2"; transcript_id "PB.2.2";
chr1    PacBio  exon    1143    2231    .       +       .       gene_id "PB.2"; transcript_id "PB.2.2";
chr1    PacBio  exon    2292    3686    .       +       .       gene_id "PB.2"; transcript_id "PB.2.2";
chr1     PacBio  transcript      1215    6942    .       +       .       gene_id "PB.2"; transcript_id "PB.2.3";
chr1     PacBio  exon    1215    2219    .       +       .       gene_id "PB.2"; transcript_id "PB.2.3";
chr1     PacBio  exon    5669    6942    .       +       .       gene_id "PB.2"; transcript_id "PB.2.3";

I cannot figure out whether there is any error in data/command prepare or not. Can anyone explain for this? 
Thanks a lot！

**Comment by Magdoll** [comment]
Hi @52teth ,

This is a known "issue" with chaining single-exon transcripts. While chaining -- establishing "equivalence" of multi-exon isoforms is much more straightforward (currently, I simply ask that all internal junctions agree), for single-exon transcripts, I currently just ask that they overlap.

This creates the weird case in which your `PB.1.1` from sample 1 is a single exon of `chr1:70-4943` but you have two separate transcripts in sample 2 `PB.1.1` and `PB.2.1` that are non-overlapping but are actually two single-exon transcripts that are each a fragment of sample 1's `PB.1.1`!

So, by the current logic of chaining, the result is correct. Because `PB.1.1` in sample1 is by current definition equivalent to both `PB.1.2` and `PB.2.1` in sample 2.

Hope this makes sense.

--liz
