### ISSUE TITLE
Hi @tomasflyo ,

### ISSUE THREAD

**Issue by tomasflyo** [Magdoll/cDNA_Cupcake#81]
Hi @tomasflyo ,
The import error comes from not having compiled/installed Cupcake.

Please follow [instructions here](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake-ToFU%3A-supporting-scripts-for-Iso-Seq-after-clustering-step#install).

Let me know how it goes.

Thanks,
--Liz

_Originally posted by @Magdoll in https://github.com/Magdoll/cDNA_Cupcake/issues/79#issuecomment-502732112_

**Comment by tomasflyo** [comment]
Hi Liz,

Thanks, installed.
Now I am getting:

> $ python demux_by_barcode_groups.py --pooled_fastx mapped.fastq mapped.fastq.sam job20190613.mapped_fl_count.txt output_demux "('151149_5p--150809_3p','150809'),('151149_5p--151149_3p','151149')"
> File "demux_by_barcode_groups.py", line 21
> raise Exception, "Unrecognized file suffix .{0}! Must end with .fasta or .fastq!".format(in_filename[in_filename.find('.'):])
> ^
> TabError: inconsistent use of tabs and spaces in indentation

thanks

**Comment by Magdoll** [comment]
Hi @tomasflyo ,
My bad - I've fixed the tab/space mixing issue in version 7.8. Please update.

--liz
