### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by ashokpatowary** [Magdoll/cDNA_Cupcake#83]
I just updated cDNA_Cupcake to the latest version and I am having the following error

pkg_resources.ResolutionError: Script 'scripts/collapse_isoforms_by_sam.py' not found in metadata at '/u/Tools/cDNA_Cupcake/cupcake.egg-info'

It was working perfect in the older version.

**Comment by Magdoll** [comment]
Hi @ashokpatowary ,

I just did a clean install and did not notice this issue. Maybe delete the old eggs in the Anaconda directory?

--Liz

**Comment by xweigit** [comment]
I got the same error when I updated cDNA_Cupcake to the latest version v12.1.0:
pkg_resources.ResolutionError: Script 'scripts/collapse_isoforms_by_sam.py' not found in metadata at '/path/to/cDNA_Cupcake/cupcake.egg-info'

It was working perfect in the older version.
Would you mind helping me to figure out how to solve the problem?

Thank you!

**Comment by mmarchin** [comment]
I have the same error.

**Comment by xweigit** [comment]
I couldn't remember the details of my comments. Would you mind giving me the link of the comments? or forward the details to me. I might get a answer.



________________________________

**Comment by mmarchin** [comment]
Sure, you said:

> I got the same error when I updated cDNA_Cupcake to the latest version v12.1.0:
> pkg_resources.ResolutionError: Script 'scripts/collapse_isoforms_by_sam.py' not found in metadata at '/path/to/cDNA_Cupcake/cupcake.egg-info'
> 
> It was working perfect in the older version.
> Would you mind helping me to figure out how to solve the problem?
> 
> Thank you!

**Comment by xweigit** [comment]
?If I remembered correctly, the error may related to multiple python installation. Our system uses module to control the versions of software packages. I switched to a later version of python on our system and tried to upgrade the cDNA_Capcake package on the later version of python. But cDNA_Capcake kept looking for the script on old version of python folder, but cannot find it.


I thought the setup of the later version python on our system maybe not completed. So I installed my own version of anaconda on my own home folder to solve the problem.

?









________________________________

**Comment by mmarchin** [comment]
Thanks. I already have my own conda installed, but I think something is going wrong. I tried removing some old environments and I am going to start with a fresh environment and install everything and see how it goes.

**Comment by xweigit** [comment]
?Good luck!

________________________________
