### ISSUE TITLE
Single Cell: Sqanti2 Update

### ISSUE THREAD

**Issue by ashokpatowary** [Magdoll/cDNA_Cupcake#85]
Hi @Magdoll 

After the latest update of SQANTI2, no *.group.txt file is generated. In this case how to related the barcode with isoform? 

Thanks

**Comment by Magdoll** [comment]
Hi @ashokpatowary ,

There appears to be some confusion. `.group.txt` file is generated by the script `collapse_isoforms_by_sam.py`. What scripts are you referring to? What commands are being run?

--Liz

**Comment by ashokpatowary** [comment]
Hi @Magdoll 

My bad. I should have closed this issue as I realized where is the problem. I run the whole pipeline in sh file. I thought its an issue with SQANTI update. But, actually, there was some issues with my collapse_isoforms_by_sam.py. I have  to run this script from cDNA_Cupcake/. This time I forgot to cd to cDNA_Cupcake location. Anyways, thank you for your quick response.
