### ISSUE TITLE
A problem of run_preCluster.py

### ISSUE THREAD

**Issue by ClearloveMiao** [Magdoll/cDNA_Cupcake#86]
Hi, @Magdoll 
I have a question about `run_preCluster.py` , how can I run it and how can I deal with this problem:
`No such file or directory: 'ids_for_NitrateReductase_gene.txt'`.
Thanks a lot!

**Comment by Magdoll** [comment]
hi @ClearloveMiao ,
This should be fixed in v8.3 of Cupcake.

Thanks,
-Liz
