### ISSUE TITLE
filter_by_count.py failed

### ISSUE THREAD

**Issue by emaleckova** [Magdoll/cDNA_Cupcake#87]
Hello,
I have been trying to run filter_by_count.py and while displaying the help for it works, running it on actual data unfortunately does not. It ends up with the following outcome:

Traceback (most recent call last):
  File "/home/bin/cDNA_Cupcake/cupcake/tofu/filter_by_count.py", line 105, in <module>
    filter_by_count(args.input_prefix, output_prefix, args.min_count, args.dun_use_group_count)
  File "/home/bin/cDNA_Cupcake/cupcake/tofu/filter_by_count.py", line 39, in filter_by_count
    fl_count, p_count = tmp.split('p')
ValueError: need more than 1 value to unpack

I tried running it both with and without --min_count and --dun_use_group_count arguments but the error message remains the same. Trying to figure out, what causes the problem I noticed that my prefix.abundance.txt file contains a column called count_fl, while the error refers to fl_count, but renaming it to fl_count did not solve the issue either. Honestly, I could not figure out where the p_count comes from and if I am possibly missing something in my data/files produced so far.

I hope I was able to provide all relevant information enabling you to help me with this issue. If something is missing, could you please let me know what is needed? I look forward to your response (and thus finishing the whole pipeline). Many thanks.

**Comment by Magdoll** [comment]
Hi @emaleckova ,
That is strange, When you run it with `--dun_use_group_count`, it should complete skip that section of the code so you should not be seeing that error.

I do not think the issue is with your count file format.

Can you show me the full command you ran?

--Liz

**Comment by emaleckova** [comment]
Hi @Magdoll and thank you for taking care of my issue so fast!

Here is the command as I tried to use it:
filter_by_count.py hq.isoforms_clean2.fasta.no5merge.collapsed --min_count=2

The full error message is:
Traceback (most recent call last):
  File "/usr/local/bin/filter_by_count.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==5.3', 'filter_by_count.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 742, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1667, in run_script
  File "/usr/local/lib/python2.7/dist-packages/cupcake-5.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/filter_by_count.py", line 105, in <module>
    filter_by_count(args.input_prefix, output_prefix, args.min_count, args.dun_use_group_count)
  File "/usr/local/lib/python2.7/dist-packages/cupcake-5.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/filter_by_count.py", line 39, in filter_by_count
    fl_count, p_count = tmp.split('p')
ValueError: need more than 1 value to unpack

Best regards,
Eva

P.S. I am sorry for not formatting the code portions appropriately but somehow, the button is not responsive in my outdated browser version.

**Comment by Magdoll** [comment]
Can you please run it with 

```
filter_by_count.py hq.isoforms_clean2.fasta.no5merge.collapsed --min_count=2 --dun_use_group_count
```

Let me know how it goes.

**Comment by emaleckova** [comment]
Hi and thank you. After running the suggested code, it still did not finish successfully but the error message changed a bit:

Traceback (most recent call last):
  File "/home/bin/cDNA_Cupcake/cupcake/tofu/filter_by_count.py", line 105, in <module>
    filter_by_count(args.input_prefix, output_prefix, args.min_count, args.dun_use_group_count)
  File "/home/bin/cDNA_Cupcake/cupcake/tofu/filter_by_count.py", line 39, in filter_by_count
    fl_count, p_count = tmp.split('p')
ValueError: need more than 1 value to unpack

While I understand there might be good reasons for filtering by abundance, I am actually more interested in having a look on (I guess, likely) 5'-end degradation of the sequenced/recovered transcripts. My understanding is that I need the outcome from filter_by_count.py for that. Am I right? Would there be a way to circumvent the abundance-based filtering step and proceed directly with filter_away_subset.py?

Thank you.

Regards,
Eva

**Comment by Magdoll** [comment]
Hi @emaleckova ,

Sorry but this error doesn't make sense to me. If you ran `--dun_use_group_count` there's simply no way you would execute that part of the code and see that error. The only reason I can imagine this happening is you have an older version of Cupcake, in which case can you please upgrade?

--Liz

**Comment by emaleckova** [comment]
Hello Liz (@Magdoll) (and others possibly facing the same issue),

I am happy to tell you I could solve my problem. It actually was a combination of two. First, after updating Cupcake (I used version 8.2 before), I could get rid of all the previous errors but a new one emerged. Getting that far was however very helpful, as it pointed me out to search further.

Here, the second issue comes. I was following the tutorial for collapsing isoforms without a genome, thus creating a FASTA file in the minimap2 step and files based on it along the way. In the end, I was thus missing the "hq.isoforms.fastq.no5merge.collapsed.rep.fq" file as an input for filter_by_count.py. After repeating the minimap2 step while producing a FASTQ file and using it as an input for collapse_isoforms_by_sam.py, filter_by_count.py eventually finished without any further issues and all the produced file looks OK.

Seems to me like I can proceed further!

Thank you, Liz for all your efforts and development of a bunch of helpful Iso-Seq tools.

Best,
Eva

**Comment by Magdoll** [comment]
Hi @emaleckova ,

Great to hear it worked and thank you for reporting back the findings.
--Liz
