### ISSUE TITLE
Issue with run_phaser.py

### ISSUE THREAD

**Issue by ashokpatowary** [Magdoll/cDNA_Cupcake#88]
Hi @Magdoll 

I am trying to run run_phaser.py. But while running its giving me error "Cannot import vcf! Please install bio-vcf!". But I am having bio-vcf
 
"bio-vcf                   0.9.2                         0    bioconda"

I am not sure what going wrong.

**Comment by Magdoll** [comment]
Hi @ashokpatowary ,

Apologies. The dependency should be [pyvcf](https://anaconda.org/bioconda/pyvcf) not bio-vcf. I have updated the wiki and code base to reflect this.
