### ISSUE TITLE
Fatal Python Error

### ISSUE THREAD

**Issue by veravelasco** [Magdoll/cDNA_Cupcake#89]
### Please help with Fatal Python Error:

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007ffff7fdd740 (most recent call first):
/var/spool/slurm/slurmd/job282715/slurm_script: line 25: 28503 Aborted                 collapse_isoforms_by_sam.py --input $CLU/m54083_190518_023003.polished.hq.fastq --fq -s $ALI/m54083_190518_023003.polished.hq_isoforms.fastq.sorted.sam --dun-merge-5-shorter -o m54083_190518_023003
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007ffff7fdd740 (most recent call first):
/var/spool/slurm/slurmd/job282715/slurm_script: line 27: 28504 Aborted                 get_abundance_post_collapse.py m54083_190518_023003.collapsed $CLU/m54083_190518_023003.polished.cluster_report.csv
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007ffff7fdd740 (most recent call first):
/var/spool/slurm/slurmd/job282715/slurm_script: line 29: 28505 Aborted                 filter_by_count.py m54083_190518_023003.collapsed --min_count=2 --dun_use_group_count
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007ffff7fdd740 (most recent call first):
/var/spool/slurm/slurmd/job282715/slurm_script: line 31: 28506 Aborted                 filter_away_subset.py m54083_190518_023003.collapsed.min_fl_2

Thanks.

**Comment by Magdoll** [comment]
Hi @veravelasco ,

This looks like SLURM job submission issues where it's missing Python dependencies. I'm afraid you would have to contact your IT/tech support for help. This is beyond my expertise.

Thanks,
--Liz

**Comment by veravelasco** [comment]
Thanks though


Get Outlook for Android<https://aka.ms/ghei36>

________________________________
