### ISSUE TITLE
How To Plot Rarefaction/Saturation Curve to assess the sequencing depth?

### ISSUE THREAD

**Issue by linglingtingfei** [Magdoll/cDNA_Cupcake#9]
@Magdoll 
I've got rarefaction file by running 'subsample.py' in the light of what you said, but I don't know what to do next for plotting  rarefaction curve. I'm trying to use iNEXT, but the input files seems to be different, Could you give me some hints? Thank you so much.

**Comment by Magdoll** [comment]
Hi @linglingtingfei ,
I don't know how to use iNext, but I have always just used either R or Microsoft Excel to plot. You can load the rarefaction txt file into Excel using Data --> From Text. Then using Chart to plot the curve similar to [tutorial here](https://www.techwalla.com/articles/how-to-plot-a-standard-curve-in-excel).
