### ISSUE TITLE
maybe a bug of get_fl_from_id in collapse_isoforms_by_sam.py 

### ISSUE THREAD

**Issue by defendant602** [Magdoll/cDNA_Cupcake#91]
Dear Liz:

I am using IsoSeq3 and I have a question about collapse_isoforms_by_sam.py.

There is a function called get_fl_from_id, which is a subfunction of collapse_fuzzy_junctions, in the code of collapse_isoforms_by_sam.py. It lools like this:
`return sum(int(_id.split('/')[1].split('p')[0][1:]) for _id in members)`

I assume it may return a wrong full_length_coverage when facing IseSeq3 id. For example, 
`"transcript/3688".split('/')[1].split('p')[0][1:]`
will return 688 other than 0.

I don't know whether I am right or I missed other code in collapse_isoforms_by_sam.py. Hope for your reply.

Thanks.

**Comment by Magdoll** [comment]
Hi @defendant602 ,
Thank you for pointing out this incorrect behavior. I have removed this piece of code and updated Cupcake to v8.5.

-Liz
