### ISSUE TITLE
Fasta input for ToFU scripts

### ISSUE THREAD

**Issue by rorycraig337** [Magdoll/cDNA_Cupcake#93]
Hi,

I have my IsoSeq data in fasta format rather than fastq, as output by the latest IsoSeq3 version. I'm running into a problem with some of the ToFU scripts, that look to be expecting .fq files (e.g. filter_away_subset.py, filter_by_count.py). 

Can these be used with fasta input? Or if they're not actually using the quality scores, would you recommend making fastq input with dummy quality values?

Many thanks,
Rory

**Comment by Magdoll** [comment]
Hi @rorycraig337 ,

You can use the [fa2fq.py script](https://github.com/Magdoll/cDNA_Cupcake/wiki/Sequence-Manipulation-Wiki#convert) in Cupcake to make dummy QVs.

Cheers,
--Liz
