### ISSUE TITLE
'Namespace' object has no attribute 'fasta'

### ISSUE THREAD

**Issue by lmurba** [Magdoll/cDNA_Cupcake#94]
I'm trying to run collapse_isoforms_by_sam.py and I am getting the following error: 
AttributeError: 'Namespace' object has no attribute 'fasta'

I ran the test data in the following way and still received the same error. 

collapse_isoforms_by_sam.py --input hq_isoforms.fastq --fq \
   -s hq_isoforms.fastq.sorted.sam --dun-merge-5-shorter -o test

Can someone help me with this issue? 
Thanks!

**Comment by Magdoll** [comment]
Hi @lmurba ,

I'm not sure I can tell what's wrong based on the command line alone (which looks fine to me).

Can you first check that both the `hq_isoforms.fastq` input fastq and the sorted SAM file `hq_isoforms.fastq.sorted.sam` look to be complete and in proper format?

If error still persists, can you provide an email so I can request a confidential file upload? I will need the fastq and the sorted sam file.

-Liz

**Comment by lmurba** [comment]
Hi @Magdoll,

I checked the hq_isoforms.fastq and hq_isoforms.fastq.sorted.sam and they both look correct to me.  I have been working with the test data to make sure the code works before feeding in my data. So the fastq and sorted sam should be the ones in the test folder provided by the tool.

-Laura

**Comment by lmurba** [comment]
@Magdoll 

As a follow-up I was looking through the collapse_isoforms_by_sam.py code and it appears the argument parser is not storing the input variable by the name fasta. Is it possible this is the issue? 

Thanks!
Laura

**Comment by Magdoll** [comment]
Hi @lmurba ,
Yeah I'm kind of confused by this error. Would you mind sending me an email so I can request file upload confidentially?
-Liz

**Comment by lmurba** [comment]
Hi @lmurba 
Sure! What's your email? Are you getting the same error with the test data? 

Thanks!
Laura

**Comment by Magdoll** [comment]
etseng@pacb.com

**Comment by sum732** [comment]
Hello  @Magdoll,
I am seeing the same issue. Was fix found?

**Comment by Magdoll** [comment]
@sum732 ,

You are providing a FASTA input so you should NOT be using the `--fq` option. Remove it.
