### ISSUE TITLE
Question about variant calls after Cupcake collapse.

### ISSUE THREAD

**Issue by WallyL** [Magdoll/cDNA_Cupcake#96]
Hi Liz,

I've processed human data from control and treated samples with the Cupcake workflow and then mapped the output fastas, i.e. polished HQ, collapsed, collapsed + filtered, against the hg38 ref and loaded them into IGV. 

One of the transcripts w/multiple exons is perfectly reconstructed; however, I don't understand how the collapse step is handling variants that are detected in the polished HQ reads.  That is, there is more evidence in the HQ read data of a variant, but the collapsed consensus transcripts end up homozygous ref.  A third variant (not shown) is seen in all HQ isoforms and it is passed on to the collapsed transcript.  I have attached 2 screen shot examples to show what I'm referring to.

![Variant_TP53_image1](https://user-images.githubusercontent.com/29130121/65896242-de80a980-e37a-11e9-8325-37d899553179.png)

![Variant_TP53_image2](https://user-images.githubusercontent.com/29130121/65896251-e17b9a00-e37a-11e9-9875-f33858d25f6b.png)

**Comment by Magdoll** [comment]
Hi @WallyL ,

The collapse script doesn't really care about variants. When it collapses a group of redundant transcripts (as seen in `xxx.group.txt`), it randomly picks one of the sequences as representative. I believe that explains the two situations you are seeing here.

If you want to retrieve the SNP information, consider look into [IsoPhase](https://github.com/Magdoll/cDNA_Cupcake/wiki/IsoPhase:-Haplotyping-using-Iso-Seq-data).

**Comment by WallyL** [comment]
Will do.  Thanks!
