### ISSUE TITLE
Isoseq single cell analysis

### ISSUE THREAD

**Issue by moschmi** [Magdoll/cDNA_Cupcake#99]
Hi Liz,
I am following your single cell isoseq pipeline. In "4. Remove polyA Tail and Artificial Concatamers". 
What primers.fasta file should I use in "isoseq3 refine"? I only want to remove the polyA tail.
I already removed the primers, UMI and BC.
I can't run isoseq3 refine without primer file.
best
Marcel

**Comment by Magdoll** [comment]
Hi @moschmi ,
The `isoseq3 refine` step uses the same primer fasta as when you ran `lima`. 

The refine step actually does two things:

- detect and remove polyA tail (remember to run with `--require-polya`)
- detect and remove concatemers, which means concatenation of multiple cDNA, and you will see this by finding cDNA primers in the middle of a sequence post-lima, hence, this is why you should supply the same primer fasta as the one you ran lima with

Hope this clarifies things.
